from pathlib import Path
p=Path('lab-selector-v4/selector-nubes-multistream-core.html')
w=Path('lab-selector-v4/index.html')
s=p.read_text(); h=w.read_text()
old="let best=null,bd=Infinity,blackHit=null,blackBd=Infinity,red48=[];const pad=15/Math.max(.1,baseRs*zoom);for(const s of classicVisual){if(x<s.bbox[0]-pad||x>s.bbox[2]+pad||y<s.bbox[1]-pad||y>s.bbox[3]+pad)continue;const d=distance(s,x,y);if(d<bd){bd=d;best=s}if(isNearBlackStroke(s)&&d<blackBd){blackBd=d;blackHit=s}const rc=(s.rgb||[]).slice(0,3).map(Number);if((s.segs||0)>0&&rc.length===3&&rc.every(Number.isFinite)&&rc[0]>=.70&&rc[0]-rc[1]>=.35&&rc[0]-rc[2]>=.35&&rc[1]<=.42&&rc[2]<=.42)red48.push({s,d})}red48.sort((a,b)=>a.d-b.d);const tol=14/Math.max(.1,baseRs*zoom);let red48Used=false;if((!best||bd>tol)&&red48.length===1&&red48[0].d<=pad){best=red48[0].s;bd=red48[0].d;red48Used=true}if(!best||bd>Math.max(tol,red48Used?pad:tol)){status.textContent='No encontré un trazo visual suficientemente cerca.';return}"
new="let best=null,bd=Infinity,blackHit=null,blackBd=Infinity,red49=[];const scale=Math.max(.1,baseRs*zoom),pad=15/scale,redPad=30/scale;for(const s of classicVisual){const rc=(s.rgb||[]).slice(0,3).map(Number),isRed=(s.segs||0)>0&&rc.length===3&&rc.every(Number.isFinite)&&rc[0]>=.70&&rc[0]-rc[1]>=.35&&rc[0]-rc[2]>=.35&&rc[1]<=.42&&rc[2]<=.42;const inNormal=!(x<s.bbox[0]-pad||x>s.bbox[2]+pad||y<s.bbox[1]-pad||y>s.bbox[3]+pad),inRed=isRed&&!(x<s.bbox[0]-redPad||x>s.bbox[2]+redPad||y<s.bbox[1]-redPad||y>s.bbox[3]+redPad);if(!inNormal&&!inRed)continue;const d=distance(s,x,y);if(inNormal){if(d<bd){bd=d;best=s}if(isNearBlackStroke(s)&&d<blackBd){blackBd=d;blackHit=s}}if(inRed&&d<=redPad)red49.push({s,d})}red49.sort((a,b)=>a.d-b.d);const tol=14/scale;let red49Used=false;if((!best||bd>tol)&&red49.length===1){best=red49[0].s;bd=red49[0].d;red49Used=true}if(!best||bd>Math.max(tol,red49Used?redPad:tol)){status.textContent='No encontré un trazo visual suficientemente cerca. · DBG49 red='+red49.length+(red49.length?' d='+red49[0].d.toFixed(2):'');return}"
assert old in s, 'flatmem48 hit block not found'
s=s.replace(old,new,1)
s=s.replace("(red48Used?' · DBG48 uniqueRed=1 d='+bd.toFixed(2)+' l='+Number(best.lines||0)+' c='+Number(best.curves||0)+' s='+Number(best.segs||0):'')","(red49Used?' · DBG49 uniqueRed=1 d='+bd.toFixed(2)+' l='+Number(best.lines||0)+' c='+Number(best.curves||0)+' s='+Number(best.segs||0):'')",1)
h=h.replace('flatmem48','flatmem49')
p.write_text(s); w.write_text(h)
