from pathlib import Path
p=Path('lab-selector-v4/selector-nubes-multistream-core.html')
w=Path('lab-selector-v4/index.html')
s=p.read_text(); h=w.read_text()
old="out.push({cmds,bbox,first,last,lines,curves,segs:lines+curves,width:Number(stroke?.lineWidth||0),rgb,closed,chordNorm:chord/d,lengthNorm:plen/d})"
assert old in s
s=s.replace(old,"out.push({cmds,bbox,first,last,lines,curves,segs:lines+curves,width:Number(stroke?.lineWidth||0),rgb,closed,chordNorm:chord/d,lengthNorm:plen/d,_ordinal:out.length})",1)
pos=s.index('function chooseClassic(e){')
block='''\nfunction red37Rgb(v){const c=(v?.rgb||[]).slice(0,3).map(Number);return c.length===3&&c.every(Number.isFinite)?c:[]}\nfunction red37Color(v){const c=red37Rgb(v);return c.length===3&&c[0]>=.72&&c[0]-c[1]>=.42&&c[0]-c[2]>=.42&&c[1]<=.36&&c[2]<=.36}\nfunction red37Piece(v){if(!red37Color(v))return false;const n=Number(v.segs||0),d=diag(v.bbox||[0,0,0,0]);return n>=1&&n<=10&&Number.isFinite(d)&&d>=.25&&v.first&&v.last}\nfunction red37Compat(x,seed){if(!red37Piece(x)||!red37Piece(seed)||colorDist(red37Rgb(x),red37Rgb(seed))>.05)return false;const dx=Math.max(.001,diag(x.bbox)),ds=Math.max(.001,diag(seed.bbox)),r=dx/ds;if(r<.12||r>8)return false;const wx=Math.abs(Number(x.width)||0),ws=Math.abs(Number(seed.width)||0);if(Math.max(wx,ws)>.04){const wr=Math.max(.001,wx)/Math.max(.001,ws);if(wr<.35||wr>2.8)return false}return true}\nfunction red37Component(seed){const sd=Math.max(.001,diag(seed.bbox)),so=Number(seed._ordinal),all=[];for(const v of classicVisual){if(!red37Compat(v,seed))continue;const od=Math.abs(Number(v._ordinal)-so);if(Number.isFinite(od)&&od<=700)all.push(v)}if(!all.includes(seed))all.push(seed);if(all.length<4)return{group:[seed],cand:all.length,extent:1,branchy:0,ordSpan:0,safe:false};const md=med(all.map(v=>diag(v.bbox)).filter(Boolean)),tol=Math.max(.55,Math.min(sd,md)*.28),cell=Math.max(.55,tol),grid=new Map(),key=(x,y)=>Math.floor(x/cell)+','+Math.floor(y/cell),put=(pt,i)=>{const k=key(pt[0],pt[1]);let a=grid.get(k);if(!a)grid.set(k,a=[]);a.push(i)};for(let i=0;i<all.length;i++){put(all[i].first,i);put(all[i].last,i)}const idx=new Map(all.map((v,i)=>[v,i])),start=idx.get(seed),seen=new Set([start]),q=[start],deg=new Map();while(q.length){const i=q.shift(),v=all[i];for(const ep of [v.first,v.last]){const cx=Math.floor(ep[0]/cell),cy=Math.floor(ep[1]/cell);for(let gx=cx-1;gx<=cx+1;gx++)for(let gy=cy-1;gy<=cy+1;gy++){for(const j of grid.get(gx+','+gy)||[]){if(j===i)continue;const u=all[j],mind=Math.min(Math.hypot(ep[0]-u.first[0],ep[1]-u.first[1]),Math.hypot(ep[0]-u.last[0],ep[1]-u.last[1]));if(mind>tol)continue;deg.set(i,(deg.get(i)||0)+1);deg.set(j,(deg.get(j)||0)+1);if(!seen.has(j)){seen.add(j);q.push(j)}}}}}}const group=[...seen].map(i=>all[i]),ds=group.map(v=>diag(v.bbox)).filter(Boolean),gm=med(ds),extent=gm?diag(componentBox(group))/gm:0,degVals=group.map(v=>deg.get(idx.get(v))||0),branchy=degVals.filter(d=>d>4).length/Math.max(1,degVals.length),ords=group.map(v=>Number(v._ordinal)).filter(Number.isFinite),ordSpan=ords.length?Math.max(...ords)-Math.min(...ords):0,safe=group.length>=6&&extent>=3.2&&branchy<=.10&&ordSpan<=700;return{group,cand:all.length,extent,branchy,ordSpan,safe,tol}}\n'''
s=s[:pos]+block+s[pos:]
old="let best=null,bd=Infinity,blackHit=null,blackBd=Infinity;const pad=15/Math.max(.1,baseRs*zoom);for(const s of classicVisual){if(x<s.bbox[0]-pad||x>s.bbox[2]+pad||y<s.bbox[1]-pad||y>s.bbox[3]+pad)continue;const d=distance(s,x,y);if(d<bd){bd=d;best=s}if(isNearBlackStroke(s)&&d<blackBd){blackBd=d;blackHit=s}}const tol=14/Math.max(.1,baseRs*zoom);if(!best||bd>tol){status.textContent='No encontré un trazo visual suficientemente cerca.';return}let prefBroad=null,prefGroups=null,prefSeed=null;if(!isNearBlackStroke(best)&&blackHit&&blackBd<=tol){"
new="let best=null,bd=Infinity,blackHit=null,blackBd=Infinity,redHits=[];const pad=15/Math.max(.1,baseRs*zoom);for(const s of classicVisual){if(x<s.bbox[0]-pad||x>s.bbox[2]+pad||y<s.bbox[1]-pad||y>s.bbox[3]+pad)continue;const d=distance(s,x,y);if(d<bd){bd=d;best=s}if(isNearBlackStroke(s)&&d<blackBd){blackBd=d;blackHit=s}if(red37Piece(s)&&d<=pad)redHits.push({s,d})}const tol=14/Math.max(.1,baseRs*zoom);if(!best||bd>tol){status.textContent='No encontré un trazo visual suficientemente cerca.';return}let prefRed37=null,red37Info=null,red37Seed=null,prefBroad=null,prefGroups=null,prefSeed=null;const sw=Math.max(2/Math.max(.1,baseRs*zoom),tol*.75),eligible=redHits.filter(q=>q.d<=Math.max(bd+sw,sw*1.5));if(eligible.length){eligible.sort((a,b)=>Number(b.s._ordinal)-Number(a.s._ordinal)||a.d-b.d);for(const q of eligible.slice(0,12)){const info=red37Component(q.s);if(info.safe){red37Seed=q.s;red37Info=info;prefRed37=info.group;best=q.s;bd=q.d;break}if(!red37Info){red37Seed=q.s;red37Info=info}}}if(!prefRed37&&!isNearBlackStroke(best)&&blackHit&&blackBd<=tol){"
assert old in s
s=s.replace(old,new,1)
old2="let famVisual=[];if(blackSeed){"
assert old2 in s
s=s.replace(old2,"let famVisual=[];if(prefRed37){famVisual=prefRed37}else if(blackSeed){",1)
old3="status.textContent='Selección acumulada · familias='+selectionFamilies+' · resaltados='+visualSelected.length+' · grupos≈'+vg+' · expansión por componente · azul listo · correspondencia estructural se calculará al pulsar Eliminar · Ctrl/Shift+clic añade otro tipo'+(blackSeed?"
assert old3 in s
s=s.replace(old3,"status.textContent='Selección acumulada · familias='+selectionFamilies+' · resaltados='+visualSelected.length+' · grupos≈'+vg+' · expansión por componente · azul listo · correspondencia estructural se calculará al pulsar Eliminar · Ctrl/Shift+clic añade otro tipo'+(prefRed37?' · DBG red37=1 seed='+prefRed37.length+' cand='+(red37Info?.cand||0)+' extent='+(red37Info?.extent||0).toFixed(2)+' branch='+(red37Info?.branchy||0).toFixed(3)+' ordSpan='+(red37Info?.ordSpan||0)+' ord='+(red37Seed?._ordinal??-1)+' rgb='+dbgRgb:(red37Seed?' · DBG red37=0 seed='+(red37Info?.group?.length||1)+' cand='+(red37Info?.cand||0)+' extent='+(red37Info?.extent||0).toFixed(2)+' branch='+(red37Info?.branchy||0).toFixed(3)+' ordSpan='+(red37Info?.ordSpan||0)+' ord='+(red37Seed?._ordinal??-1)+' rgb='+dbgRgb:(blackSeed?",1)
tail="' · DBG blackSeed=0 rgb='+dbgRgb)}"
assert tail in s
s=s.replace(tail,"' · DBG blackSeed=0 rgb='+dbgRgb)))}",1)
h=h.replace('flatmem20','flatmem37',1) if 'flatmem20' in h else h.replace('selector-nubes-multistream-core.html?v=', 'selector-nubes-multistream-core.html?v=20260908-flatmem37-',1)
p.write_text(s); w.write_text(h)
