import * as mupdf from 'https://cdn.jsdelivr.net/npm/mupdf@1.28.0/dist/mupdf.js';
import JSZip from 'https://esm.sh/jszip@3.10.1';

const findInput=document.querySelector('#findText'),replaceInput=document.querySelector('#replaceText'),fileInput=document.querySelector('#textFileInput'),dropzone=document.querySelector('#textDropzone'),openBtn=document.querySelector('#textOpenBtn'),processBtn=document.querySelector('#textProcessBtn'),clearBtn=document.querySelector('#textClearBtn'),status=document.querySelector('#textStatus'),summary=document.querySelector('#textSummary'),results=document.querySelector('#textResults');
let entries=[];const canWriteOriginals='showOpenFilePicker'in window;
function setStatus(m,t=''){status.textContent=m;status.className=`status ${t}`.trim()}
function updateControls(){processBtn.disabled=!findInput.value.trim()||!entries.length;clearBtn.disabled=!entries.length&&!findInput.value&&!replaceInput.value}
function addFiles(list){const next=[...list].filter(f=>f.type==='application/pdf'||f.name.toLowerCase().endsWith('.pdf')).map(file=>({name:file.name,file,direct:false}));const map=new Map(entries.map(x=>[x.name,x]));next.forEach(x=>map.set(x.name,x));entries=[...map.values()];summary.classList.add('hidden');results.innerHTML='';setStatus(`${entries.length} PDF${entries.length===1?'':'s'} seleccionado${entries.length===1?'':'s'}.`);updateControls()}
async function openHandles(){if(!canWriteOriginals){fileInput.click();return}try{const hs=await window.showOpenFilePicker({multiple:true,excludeAcceptAllOption:true,types:[{description:'PDF',accept:{'application/pdf':['.pdf']}}]});entries=[];for(const handle of hs){const file=await handle.getFile();entries.push({name:file.name,file,handle,direct:true})}summary.classList.add('hidden');results.innerHTML='';setStatus(`${entries.length} PDF${entries.length===1?'':'s'} seleccionado${entries.length===1?'':'s'} · se guardarán sobre los originales.`);updateControls()}catch(e){if(e?.name!=='AbortError')setStatus(`No se pudieron abrir los PDFs: ${e?.message||e}`,'warning')}}
function rectFromHit(hit){let r=null;for(const q of hit){if(!q||q.length<8)continue;const x0=Math.min(q[0],q[2],q[4],q[6]),y0=Math.min(q[1],q[3],q[5],q[7]),x1=Math.max(q[0],q[2],q[4],q[6]),y1=Math.max(q[1],q[3],q[5],q[7]);r=r?[Math.min(r[0],x0),Math.min(r[1],y0),Math.max(r[2],x1),Math.max(r[3],y1)]:[x0,y0,x1,y1]}return r}
function redactAll(doc,find){const changes=[];for(let i=0;i<doc.countPages();i++){const page=doc.loadPage(i);try{const hits=page.search(find,500);if(!hits.length)continue;const rects=hits.map(rectFromHit).filter(Boolean);for(const r of rects){const a=page.createAnnotation('Redact');a.setRect(r);a.update()}page.applyRedactions(false,mupdf.PDFPage.REDACT_IMAGE_NONE,mupdf.PDFPage.REDACT_LINE_ART_NONE,mupdf.PDFPage.REDACT_TEXT_REMOVE);changes.push({pageIndex:i,rects})}finally{page.destroy()}}return changes}
function addEditableText(doc,change,replacement){const page=doc.loadPage(change.pageIndex);const added=[];try{const bounds=page.getBounds();for(const r of change.rects){const h=Math.max(8,r[3]-r[1]);const fontSize=Math.max(6,Math.min(72,h*0.82));const estimatedWidth=Math.max(r[2]-r[0]+8,replacement.length*fontSize*0.52+10);const right=Math.min(bounds[2]-2,r[0]+estimatedWidth);const box=[r[0],r[1],Math.max(r[2]+4,right),r[3]+2];const annot=page.createAnnotation('FreeText');annot.setRect(box);annot.setContents(replacement);annot.setDefaultAppearance('Helv',fontSize,[0,0,0]);annot.setBorderWidth(0);annot.setFlags(4);annot.update();added.push(annot)}return added}finally{page.destroy()}}
function findReplacementAnnotations(doc,replacement){let found=0;for(let i=0;i<doc.countPages();i++){const page=doc.loadPage(i);try{for(const annot of page.getAnnotations()){if(annot.getType()==='FreeText'&&annot.getContents()===replacement)found++}}finally{page.destroy()}}return found}
function countStructured(doc,needle){if(!needle)return 0;let n=0;for(let i=0;i<doc.countPages();i++){const p=doc.loadPage(i);try{n+=(p.toStructuredText('preserve-whitespace').asText().split(needle).length-1)}finally{p.destroy()}}return n}
async function processPdf(entry,find,replacement){let source=entry.file;if(entry.handle){if(await entry.handle.requestPermission({mode:'read'})!=='granted')throw Error('El navegador no concedió permiso de lectura.');source=await entry.handle.getFile()}if(find===replacement)throw Error('El texto a buscar y el reemplazo son iguales; no se hizo ningún cambio.');const original=new Uint8Array(await source.arrayBuffer());const sourceDoc=mupdf.PDFDocument.openDocument(original,'application/pdf');let changes;try{changes=redactAll(sourceDoc,find);const count=changes.reduce((n,c)=>n+c.rects.length,0);if(!count){sourceDoc.destroy();return{...entry,bytes:original,count:0,changed:false}}const redactedBytes=sourceDoc.saveToBuffer('garbage=2,compress=yes').asUint8Array();sourceDoc.destroy();const doc=mupdf.PDFDocument.openDocument(redactedBytes,'application/pdf');try{let inserted=0;for(const change of changes)inserted+=addEditableText(doc,change,replacement).length;if(inserted!==count)throw Error(`Solo se pudieron crear ${inserted} cajas de texto de ${count} coincidencias.`);const bytes=doc.saveToBuffer('garbage=2,compress=yes').asUint8Array();const check=mupdf.PDFDocument.openDocument(bytes,'application/pdf');try{const oldLeft=countStructured(check,find);const newAnnotations=findReplacementAnnotations(check,replacement);if(oldLeft)throw Error(`La verificación encontró ${oldLeft} coincidencia${oldLeft===1?'':'s'} del texto antiguo.`);if(newAnnotations<count)throw Error(`La sustitución visual no quedó guardada: se encontraron ${newAnnotations} cajas de texto y se esperaban ${count}.`)}finally{check.destroy()}return{...entry,bytes,count,changed:true,original,find,replacement}}finally{doc.destroy()}}catch(e){try{sourceDoc.destroy()}catch(_){ }throw e}}
async function saveDirect(item){if(!item.changed)return;if(await item.handle.requestPermission({mode:'readwrite'})!=='granted')throw Error('El navegador no concedió permiso de escritura.');const w=await item.handle.createWritable();try{await w.write(item.bytes);await w.close()}catch(e){try{await w.abort()}catch(_){}throw e}const saved=new Uint8Array(await(await item.handle.getFile()).arrayBuffer()),check=mupdf.PDFDocument.openDocument(saved,'application/pdf');try{const oldLeft=countStructured(check,item.find),newAnnotations=findReplacementAnnotations(check,item.replacement);if(oldLeft||newAnnotations<item.count){const restore=await item.handle.createWritable();await restore.write(item.original);await restore.close();throw Error(`La verificación del archivo guardado falló: texto antiguo restante=${oldLeft}, cajas de reemplazo=${newAnnotations}. Se restauró el original.`)}}finally{check.destroy()}}
function downloadPdf(item){const u=URL.createObjectURL(new Blob([item.bytes],{type:'application/pdf'})),a=document.createElement('a');a.href=u;a.download=item.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500)}
async function downloadZip(items){const zip=new JSZip();items.forEach(x=>zip.file(x.name,x.bytes));const blob=await zip.generateAsync({type:'blob',compression:'STORE'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='pdfs-texto-reemplazado.zip';a.click();setTimeout(()=>URL.revokeObjectURL(u),1500)}
function render(item){const row=document.createElement('div');row.className=`result-row ${item.error?'error':''}`;row.innerHTML='<span class="filename"></span><span class="count"></span>';row.querySelector('.filename').textContent=item.name;row.querySelector('.count').textContent=item.error?`Error: ${item.errorMessage}`:item.count===0?'Sin coincidencias':`${item.count} reemplazada${item.count===1?'':'s'}${item.direct?' · guardado':''}`;results.appendChild(row)}
async function processAll(){const find=findInput.value,replacement=replaceInput.value;if(!find.trim()||!entries.length)return;processBtn.disabled=true;clearBtn.disabled=true;results.innerHTML='';summary.classList.add('hidden');let total=0,changed=0,ok=0,failed=0;const downloads=[];for(let i=0;i<entries.length;i++){const entry=entries[i];setStatus(`Editando ${i+1} de ${entries.length}: ${entry.name}`);try{const item=await processPdf(entry,find,replacement);if(item.direct)await saveDirect(item);else if(item.changed)downloads.push(item);total+=item.count;if(item.changed)changed++;ok++;render(item);await new Promise(r=>setTimeout(r,0))}catch(err){failed++;render({name:entry.name,error:true,errorMessage:err?.message||String(err)});console.error(`No se pudo procesar ${entry.name}`,err)}}summary.textContent=`${ok} PDF${ok===1?'':'s'} procesado${ok===1?'':'s'} · ${total} coincidencia${total===1?'':'s'} reemplazada${total===1?'':'s'} · ${changed} archivo${changed===1?'':'s'} modificado${changed===1?'':'s'}${failed?` · ${failed} con error`:''}`;summary.classList.remove('hidden');setStatus(failed?`Proceso terminado con ${failed} error${failed===1?'':'es'}. Los archivos que fallaron no se sobrescribieron.`:'Proceso terminado correctamente.',failed?'warning':'success');clearBtn.disabled=false;processBtn.disabled=false;if(downloads.length===1&&failed===0)downloadPdf(downloads[0]);else if(downloads.length>1)await downloadZip(downloads)}
function clearAll(){entries=[];findInput.value='';replaceInput.value='';fileInput.value='';summary.classList.add('hidden');results.innerHTML='';setStatus('');updateControls()}
openBtn?.addEventListener('click',openHandles);fileInput?.addEventListener('change',e=>addFiles(e.target.files));dropzone?.addEventListener('dragover',e=>{e.preventDefault();dropzone.classList.add('dragging')});dropzone?.addEventListener('dragleave',()=>dropzone.classList.remove('dragging'));dropzone?.addEventListener('drop',e=>{e.preventDefault();dropzone.classList.remove('dragging');addFiles(e.dataTransfer.files)});processBtn?.addEventListener('click',processAll);clearBtn?.addEventListener('click',clearAll);findInput?.addEventListener('input',updateControls);replaceInput?.addEventListener('input',updateControls);updateControls();