import * as mupdf from 'https://cdn.jsdelivr.net/npm/mupdf@1.28.0/dist/mupdf.js';
import JSZip from 'https://esm.sh/jszip@3.10.1';

const $=s=>document.querySelector(s),findInput=$('#findText'),replaceInput=$('#replaceText'),fileInput=$('#textFileInput'),dropzone=$('#textDropzone'),openBtn=$('#textOpenBtn'),processBtn=$('#textProcessBtn'),clearBtn=$('#textClearBtn'),status=$('#textStatus'),summary=$('#textSummary'),results=$('#textResults');
let entries=[]; const canWriteOriginals='showOpenFilePicker' in window;
function setStatus(m,t=''){status.textContent=m;status.className=`status ${t}`.trim()}
function updateControls(){processBtn.disabled=!findInput.value.trim()||!entries.length;clearBtn.disabled=!entries.length&&!findInput.value&&!replaceInput.value}
function addFiles(list){const next=[...list].filter(f=>f.type==='application/pdf'||f.name.toLowerCase().endsWith('.pdf')).map(file=>({name:file.name,file,direct:false}));const map=new Map(entries.map(x=>[x.name,x]));next.forEach(x=>map.set(x.name,x));entries=[...map.values()];results.innerHTML='';summary.classList.add('hidden');setStatus(`${entries.length} PDF${entries.length===1?'':'s'} seleccionado${entries.length===1?'':'s'}.`);updateControls()}
async function openHandles(){if(!canWriteOriginals){fileInput.click();return}try{const hs=await showOpenFilePicker({multiple:true,excludeAcceptAllOption:true,types:[{description:'PDF',accept:{'application/pdf':['.pdf']}}]});entries=[];for(const handle of hs){entries.push({name:(await handle.getFile()).name,file:await handle.getFile(),handle,direct:true})}results.innerHTML='';summary.classList.add('hidden');setStatus(`${entries.length} PDF${entries.length===1?'':'s'} seleccionado${entries.length===1?'':'s'} · se guardarán sobre los originales.`);updateControls()}catch(e){if(e?.name!=='AbortError')setStatus(`No se pudieron abrir los PDFs: ${e?.message||e}`,'warning')}}
function rectFromHit(hit){let r=null;for(const q of hit){if(!q||q.length<8)continue;const xs=[q[0],q[2],q[4],q[6]],ys=[q[1],q[3],q[5],q[7]],x=[Math.min(...xs),Math.min(...ys),Math.max(...xs),Math.max(...ys)];r=r?[Math.min(r[0],x[0]),Math.min(r[1],x[1]),Math.max(r[2],x[2]),Math.max(r[3],x[3])]:x}return r}
function pdfHex(text){let h='';for(const ch of text){const cp=ch.codePointAt(0);if(cp>255)throw Error(`El reemplazo contiene «${ch}», que no puede escribirse con la fuente Latin.`);h+=cp.toString(16).padStart(2,'0')}return `<${h}>`}
function ensureFont(doc,pageObj){let resources=pageObj.get('Resources');if(!resources||resources.isNull()){const inherited=pageObj.getInheritable('Resources');resources=inherited&&!inherited.isNull()?doc.graftObject(inherited):doc.newDictionary();pageObj.put('Resources',resources)}else if(resources.isIndirect?.()){resources=doc.graftObject(resources);pageObj.put('Resources',resources)}let fonts=resources.get('Font');if(!fonts||fonts.isNull()){fonts=doc.newDictionary();resources.put('Font',fonts)}else if(fonts.isIndirect?.()){fonts=doc.graftObject(fonts);resources.put('Font',fonts)}const name='PDFToolsHelvetica';if(!fonts.get(name)||fonts.get(name).isNull())fonts.put(name,doc.addSimpleFont(new mupdf.Font('Helvetica'),'Latin'));pageObj.put('Resources',resources);return name}
function appendStream(doc,pageObj,s){const extra=doc.addStream(s,{}),contents=pageObj.get('Contents');if(!contents||contents.isNull())pageObj.put('Contents',extra);else if(contents.isArray())contents.push(extra);else{const a=doc.newArray();a.push(contents);a.push(extra);pageObj.put('Contents',a)}}
function insertText(doc,page,pageObj,text,rect){const size=Math.max(6,Math.min(72,Math.abs(rect[3]-rect[1])*.86));const fontName=ensureFont(doc,pageObj);const bounds=page.getBounds();const x=rect[0];const y=bounds[3]-(rect[1]+size);const stream=`q BT /${fontName} ${size.toFixed(2)} Tf 0 0 0 rg 0 0 Td ${x.toFixed(2)} ${y.toFixed(2)} Td ${pdfHex(text)} Tj ET Q\n`;appendStream(doc,pageObj,stream)}
function replaceOnPage(doc,page,find,replacement){const hits=page.search(find,500);if(!hits.length)return 0;const rects=hits.map(rectFromHit).filter(Boolean);for(const r of rects){const a=page.createAnnotation('Redact');a.setRect(r);a.update()}page.applyRedactions(false,mupdf.PDFPage.REDACT_IMAGE_NONE,mupdf.PDFPage.REDACT_LINE_ART_NONE,mupdf.PDFPage.REDACT_TEXT_REMOVE);if(!replacement)return rects.length;const pageObj=page.getObject();for(const r of rects)insertText(doc,page,pageObj,replacement,r);return rects.length}
function countHits(doc,needle){if(!needle)return 0;let n=0;for(let i=0;i<doc.countPages();i++){const p=doc.loadPage(i);try{n+=p.search(needle,500).length}finally{p.destroy()}}return n}
async function processPdf(entry,find,replacement){let source=entry.file;if(entry.handle){if(await entry.handle.requestPermission({mode:'read'})!=='granted')throw Error('El navegador no concedió permiso de lectura.');source=await entry.handle.getFile()}if(find===replacement)throw Error('El texto a buscar y el reemplazo son iguales.');const original=new Uint8Array(await source.arrayBuffer()),doc=mupdf.PDFDocument.openDocument(original,'application/pdf');try{let count=0;for(let i=0;i<doc.countPages();i++){const p=doc.loadPage(i);try{count+=replaceOnPage(doc,p,find,replacement)}finally{p.destroy()}}if(!count)return{...entry,bytes:original,count:0,changed:false};const bytes=doc.saveToBuffer('garbage=2,compress=yes').asUint8Array(),check=mupdf.PDFDocument.openDocument(bytes,'application/pdf');try{const oldLeft=countHits(check,find),newFound=countHits(check,replacement);if(oldLeft)throw Error(`La verificación encontró ${oldLeft} coincidencia${oldLeft===1?'':'s'} del texto antiguo.`);if(replacement&&newFound<count)throw Error(`La verificación no encontró el reemplazo. Encontró ${newFound} de ${count}.`)}finally{check.destroy()}return{...entry,bytes,count,changed:true,original,find}}finally{doc.destroy()}}
async function saveDirect(item){if(!item.changed)return;if(await item.handle.requestPermission({mode:'readwrite'})!=='granted')throw Error('El navegador no concedió permiso de escritura.');const w=await item.handle.createWritable();try{await w.write(item.bytes);await w.close()}catch(e){try{await w.abort()}catch(_){}throw e}}
function downloadPdf(item){const u=URL.createObjectURL(new Blob([item.bytes],{type:'application/pdf'})),a=document.createElement('a');a.href=u;a.download=item.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500)}
async function downloadZip(items){const zip=new JSZip();items.forEach(x=>zip.file(x.name,x.bytes));const blob=await zip.generateAsync({type:'blob',compression:'STORE'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='pdfs-texto-reemplazado.zip';a.click();setTimeout(()=>URL.revokeObjectURL(u),1500)}
function render(item){const row=document.createElement('div');row.className=`result-row ${item.error?'error':''}`;row.innerHTML='<span class="filename"></span><span class="count"></span>';row.querySelector('.filename').textContent=item.name;row.querySelector('.count').textContent=item.error?`Error: ${item.errorMessage}`:item.count===0?'Sin coincidencias':`${item.count} reemplazada${item.count===1?'':'s'}${item.direct?' · guardado':''}`;results.appendChild(row)}
async function processAll(){const find=findInput.value,replacement=replaceInput.value;if(!find.trim()||!entries.length)return;processBtn.disabled=true;clearBtn.disabled=true;results.innerHTML='';summary.classList.add('hidden');let total=0,changed=0,ok=0,failed=0;const downloads=[];for(let i=0;i<entries.length;i++){const entry=entries[i];setStatus(`Reemplazando ${i+1} de ${entries.length}: ${entry.name}`);try{const item=await processPdf(entry,find,replacement);if(item.direct)await saveDirect(item);else if(item.changed)downloads.push(item);total+=item.count;if(item.changed)changed++;ok++;render(item);await new Promise(r=>setTimeout(r,0))}catch(err){failed++;render({name:entry.name,error:true,errorMessage:err?.message||String(err)});console.error(err)}}summary.textContent=`${ok} PDF${ok===1?'':'s'} procesado${ok===1?'':'s'} · ${total} coincidencia${total===1?'':'s'} reemplazada${total===1?'':'s'} · ${changed} archivo${changed===1?'':'s'} modificado${changed===1?'':'s'}${failed?` · ${failed} con error`:''}`;summary.classList.remove('hidden');setStatus(failed?`Proceso terminado con ${failed} error${failed===1?'':'es'}.`:'Proceso terminado correctamente.',failed?'warning':'success');clearBtn.disabled=false;processBtn.disabled=false;if(downloads.length===1&&failed===0)downloadPdf(downloads[0]);else if(downloads.length>1)await downloadZip(downloads)}
function clearAll(){entries=[];findInput.value='';replaceInput.value='';fileInput.value='';summary.classList.add('hidden');results.innerHTML='';setStatus('');updateControls()}
openBtn?.addEventListener('click',openHandles);fileInput?.addEventListener('change',e=>addFiles(e.target.files));dropzone?.addEventListener('dragover',e=>{e.preventDefault();dropzone.classList.add('dragging')});dropzone?.addEventListener('dragleave',()=>dropzone.classList.remove('dragging'));dropzone?.addEventListener('drop',e=>{e.preventDefault();dropzone.classList.remove('dragging');addFiles(e.dataTransfer.files)});processBtn?.addEventListener('click',processAll);clearBtn?.addEventListener('click',clearAll);findInput?.addEventListener('input',updateControls);replaceInput?.addEventListener('input',updateControls);updateControls();