import * as mupdf from 'https://cdn.jsdelivr.net/npm/mupdf@1.28.0/dist/mupdf.js';
import JSZip from 'https://esm.sh/jszip@3.10.1';

const findInput=document.querySelector('#findText'),replaceInput=document.querySelector('#replaceText'),fileInput=document.querySelector('#textFileInput'),dropzone=document.querySelector('#textDropzone'),openBtn=document.querySelector('#textOpenBtn'),processBtn=document.querySelector('#textProcessBtn'),clearBtn=document.querySelector('#textClearBtn'),status=document.querySelector('#textStatus'),summary=document.querySelector('#textSummary'),results=document.querySelector('#textResults');
let entries=[];const canWriteOriginals='showOpenFilePicker'in window;
function setStatus(m,t=''){status.textContent=m;status.className=`status ${t}`.trim()}
function updateControls(){processBtn.disabled=!findInput.value.trim()||!entries.length;clearBtn.disabled=!entries.length&&!findInput.value&&!replaceInput.value}
function addFiles(list){const next=[...list].filter(f=>f.type==='application/pdf'||f.name.toLowerCase().endsWith('.pdf')).map(file=>({name:file.name,file,direct:false}));const map=new Map(entries.map(x=>[x.name,x]));next.forEach(x=>map.set(x.name,x));entries=[...map.values()];summary.classList.add('hidden');results.innerHTML='';setStatus(`${entries.length} PDF${entries.length===1?'':'s'} seleccionado${entries.length===1?'':'s'}.`);updateControls()}
async function openHandles(){if(!canWriteOriginals){fileInput.click();return}try{const hs=await window.showOpenFilePicker({multiple:true,excludeAcceptAllOption:true,types:[{description:'PDF',accept:{'application/pdf':['.pdf']}}]});entries=[];for(const handle of hs){const file=await handle.getFile();entries.push({name:file.name,file,handle,direct:true})}summary.classList.add('hidden');results.innerHTML='';setStatus(`${entries.length} PDF${entries.length===1?'':'s'} seleccionado${entries.length===1?'':'s'} · se guardarán sobre los originales.`);updateControls()}catch(e){if(e?.name!=='AbortError')setStatus(`No se pudieron abrir los PDFs: ${e?.message||e}`,'warning')}}
function rectFromHit(hit){let r=null;for(const q of hit){const x=mupdf.Rect.rectFromQuad(q);r=r?[Math.min(r[0],x[0]),Math.min(r[1],x[1]),Math.max(r[2],x[2]),Math.max(r[3],x[3])]:x}return r}
function pdfRect(page,r){return mupdf.Rect.transform(r,page.getTransform())}
const WIN1252=new Map([['€',0x80],['‚',0x82],['ƒ',0x83],['„',0x84],['…',0x85],['†',0x86],['‡',0x87],['ˆ',0x88],['‰',0x89],['Š',0x8a],['‹',0x8b],['Œ',0x8c],['Ž',0x8e],['‘',0x91],['’',0x92],['“',0x93],['”',0x94],['•',0x95],['–',0x96],['—',0x97],['˜',0x98],['™',0x99],['š',0x9a],['›',0x9b],['œ',0x9c],['ž',0x9e],['Ÿ',0x9f]]);
function encodeWinAnsi(text){const out=[];for(const ch of text){const extra=WIN1252.get(ch);if(extra!=null){out.push(extra);continue}const cp=ch.codePointAt(0);if(cp<=255){out.push(cp);continue}throw new Error(`El reemplazo contiene el carácter «${ch}», que no puede escribirse con la fuente Latin seleccionada.`)}return new Uint8Array(out)}
function pdfLiteral(bytes){let s='';for(const b of bytes){if(b===40)s+='\\(';else if(b===41)s+='\\)';else if(b===92)s+='\\\\';else if(b===10)s+='\\n';else if(b===13)s+='\\r';else if(b===9)s+='\\t';else if(b<32||b>126)s+='\\'+b.toString(8).padStart(3,'0');else s+=String.fromCharCode(b)}return `(${s})`}
function ensureFont(doc,pageObj){let res=pageObj.get('Resources')||pageObj.getInheritable('Resources');res=res?doc.graftObject(res):doc.newDictionary();let fonts=res.get('Font');fonts=fonts?doc.graftObject(fonts):doc.newDictionary();const name='PDFToolsHelvetica';if(!fonts.get(name))fonts.put(name,doc.addSimpleFont(new mupdf.Font('Helvetica'),'Latin'));res.put('Font',fonts);pageObj.put('Resources',res);return name}
function appendStream(doc,pageObj,s){const ref=doc.addStream(new TextEncoder().encode(s));const c=pageObj.get('Contents');if(c?.isArray?.())c.push(ref);else if(c){const a=doc.newArray();a.push(c);a.push(ref);pageObj.put('Contents',a)}else pageObj.put('Contents',ref)}
function replaceOnPage(doc,page,find,replacement){const hits=page.search(find,500);if(!hits.length)return 0;const pageObj=page.getObject(),rects=hits.map(rectFromHit).filter(Boolean);for(const r of rects){const redact=page.createAnnotation('Redaction');redact.setRect(r);redact.update()}page.applyRedactions(false,mupdf.PDFPage.REDACT_IMAGE_NONE,mupdf.PDFPage.REDACT_LINE_ART_NONE,mupdf.PDFPage.REDACT_TEXT_REMOVE);if(!replacement)return rects.length;const fontName=ensureFont(doc,pageObj),encoded=encodeWinAnsi(replacement);for(const r0 of rects){const r=pdfRect(page,r0),h=Math.max(6,Math.min(72,Math.abs(r[3]-r[1])*.86)),x=r[0],y=Math.min(r[1],r[3])+.15*h;appendStream(doc,pageObj,`q BT /${fontName} ${h.toFixed(2)} Tf 0 g 1 0 0 1 ${x.toFixed(2)} ${y.toFixed(2)} Tm ${pdfLiteral(encoded)} Tj ET Q\n`)}return rects.length}
function countHits(doc,needle){if(!needle)return 0;let n=0;for(let i=0;i<doc.countPages();i++){const p=doc.loadPage(i);try{n+=p.search(needle,500).length}finally{p.destroy()}}return n}
async function processPdf(entry,find,replacement){let source=entry.file;if(entry.handle){if(await entry.handle.requestPermission({mode:'read'})!=='granted')throw Error('El navegador no concedió permiso de lectura.');source=await entry.handle.getFile()}if(find===replacement)throw Error('El texto a buscar y el reemplazo son iguales; no se hizo ningún cambio.');const original=new Uint8Array(await source.arrayBuffer()),doc=mupdf.PDFDocument.openDocument(original,'application/pdf');try{const beforeNew=countHits(doc,replacement);let count=0;for(let i=0;i<doc.countPages();i++){const p=doc.loadPage(i);try{count+=replaceOnPage(doc,p,find,replacement)}finally{p.destroy()}}if(!count)return{...entry,bytes:original,count:0,changed:false};const bytes=doc.saveToBuffer('garbage=2,compress=yes').asUint8Array(),check=mupdf.PDFDocument.openDocument(bytes,'application/pdf');try{const oldLeft=countHits(check,find),newFound=countHits(check,replacement);if(oldLeft)throw Error(`La verificación encontró ${oldLeft} coincidencia${oldLeft===1?'':'s'} del texto antiguo.`);if(replacement&&newFound<beforeNew+count)throw Error('La verificación no encontró todas las apariciones nuevas esperadas del reemplazo. No se sobrescribió el original.')}finally{check.destroy()}return{...entry,bytes,count,changed:true,original,find,replacement}}finally{doc.destroy()}}
async function saveDirect(item){if(!item.changed)return;if(await item.handle.requestPermission({mode:'readwrite'})!=='granted')throw Error('El navegador no concedió permiso de escritura.');const w=await item.handle.createWritable();try{await w.write(item.bytes);await w.close()}catch(e){try{await w.abort()}catch(_){}throw e}const saved=new Uint8Array(await(await item.handle.getFile()).arrayBuffer()),check=mupdf.PDFDocument.openDocument(saved,'application/pdf');try{const oldLeft=countHits(check,item.find);if(oldLeft){const restore=await item.handle.createWritable();await restore.write(item.original);await restore.close();throw Error(`La verificación del archivo guardado encontró ${oldLeft} coincidencia${oldLeft===1?'':'s'} del texto antiguo; se restauró el original.`)}}finally{check.destroy()}}
function downloadPdf(item){const u=URL.createObjectURL(new Blob([item.bytes],{type:'application/pdf'})),a=document.createElement('a');a.href=u;a.download=item.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500)}
async function downloadZip(items){const zip=new JSZip();items.forEach(x=>zip.file(x.name,x.bytes));const blob=await zip.generateAsync({type:'blob',compression:'STORE'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='pdfs-texto-reemplazado.zip';a.click();setTimeout(()=>URL.revokeObjectURL(u),1500)}
function render(item){const row=document.createElement('div');row.className=`result-row ${item.error?'error':''}`;row.innerHTML='<span class="filename"></span><span class="count"></span>';row.querySelector('.filename').textContent=item.name;row.querySelector('.count').textContent=item.error?`Error: ${item.errorMessage}`:item.count===0?'Sin coincidencias':`${item.count} reemplazada${item.count===1?'':'s'}${item.direct?' · guardado':''}`;results.appendChild(row)}
async function processAll(){const find=findInput.value,replacement=replaceInput.value;if(!find.trim()||!entries.length)return;processBtn.disabled=true;clearBtn.disabled=true;results.innerHTML='';summary.classList.add('hidden');let total=0,changed=0,ok=0,failed=0;const downloads=[];for(let i=0;i<entries.length;i++){const entry=entries[i];setStatus(`Reemplazando ${i+1} de ${entries.length}: ${entry.name}`);try{const item=await processPdf(entry,find,replacement);if(item.direct)await saveDirect(item);else if(item.changed)downloads.push(item);total+=item.count;if(item.changed)changed++;ok++;render(item);await new Promise(r=>setTimeout(r,0))}catch(err){failed++;render({name:entry.name,error:true,errorMessage:err?.message||String(err)});console.error(`No se pudo procesar ${entry.name}`,err)}}summary.textContent=`${ok} PDF${ok===1?'':'s'} procesado${ok===1?'':'s'} · ${total} coincidencia${total===1?'':'s'} reemplazada${total===1?'':'s'} · ${changed} archivo${changed===1?'':'s'} modificado${changed===1?'':'s'}${failed?` · ${failed} con error`:''}`;summary.classList.remove('hidden');setStatus(failed?`Proceso terminado con ${failed} error${failed===1?'':'es'}. Los archivos que fallaron no se sobrescribieron.`:'Proceso terminado correctamente.',failed?'warning':'success');clearBtn.disabled=false;processBtn.disabled=false;if(downloads.length===1&&failed===0)downloadPdf(downloads[0]);else if(downloads.length>1)await downloadZip(downloads)}
function clearAll(){entries=[];findInput.value='';replaceInput.value='';fileInput.value='';summary.classList.add('hidden');results.innerHTML='';setStatus('');updateControls()}
openBtn?.addEventListener('click',openHandles);fileInput?.addEventListener('change',e=>addFiles(e.target.files));dropzone?.addEventListener('dragover',e=>{e.preventDefault();dropzone.classList.add('dragging')});dropzone?.addEventListener('dragleave',()=>dropzone.classList.remove('dragging'));dropzone?.addEventListener('drop',e=>{e.preventDefault();dropzone.classList.remove('dragging');addFiles(e.dataTransfer.files)});processBtn?.addEventListener('click',processAll);clearBtn?.addEventListener('click',clearAll);findInput?.addEventListener('input',updateControls);replaceInput?.addEventListener('input',updateControls);updateControls();
