from pathlib import Path
p=Path('selector-nubes-multistream-core.html')
s=p.read_text()
a=s.index('function collectVisual(page){')
b=s.index('function distSeg(',a)
new=r'''function collectVisual(page){const out=[],cb={strokePath(path,stroke,ctm,cs,color){const cmds=[],pts=[];let first=null,last=null,lines=0,curves=0,explicitClosed=false;const P=(x,y)=>tf(ctm,x,y),add=p=>{pts.push(p);if(!first)first=p;last=p};path.walk({moveTo(x,y){const p=P(x,y);cmds.push(['M',...p]);add(p)},lineTo(x,y){const p=P(x,y);cmds.push(['L',...p]);add(p);lines++},curveTo(x1,y1,x2,y2,x3,y3){const a=P(x1,y1),b=P(x2,y2),c=P(x3,y3);cmds.push(['C',...a,...b,...c]);pts.push(a,b,c);if(!first)first=c;last=c;curves++},closePath(){cmds.push(['Z']);explicitClosed=true}});if(!pts.length)return;const xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),bbox=[Math.min(...xs),Math.min(...ys),Math.max(...xs),Math.max(...ys)],rgb=Array.isArray(color)?color.slice(0,3).map(Number):[],d=Math.max(.001,diag(bbox)),chord=first&&last?Math.hypot(last[0]-first[0],last[1]-first[1]):0;let plen=0,cur=null,start=null;for(const c of cmds){if(c[0]==='M'){cur=[c[1],c[2]];start=cur}else if(c[0]==='L'&&cur){const q=[c[1],c[2]];plen+=Math.hypot(q[0]-cur[0],q[1]-cur[1]);cur=q}else if(c[0]==='C'&&cur){const p0=cur,p1=[c[1],c[2]],p2=[c[3],c[4]],p3=[c[5],c[6]];let q=p0;for(let k=1;k<=8;k++){const t=k/8,u=1-t,n=[u*u*u*p0[0]+3*u*u*t*p1[0]+3*u*t*t*p2[0]+t*t*t*p3[0],u*u*u*p0[1]+3*u*u*t*p1[1]+3*u*t*t*p2[1]+t*t*t*p3[1]];plen+=Math.hypot(n[0]-q[0],n[1]-q[1]);q=n}cur=p3}else if(c[0]==='Z'&&cur&&start){plen+=Math.hypot(start[0]-cur[0],start[1]-cur[1]);cur=start}}const closed=explicitClosed||chord/d<=.045;out.push({cmds,bbox,first,last,lines,curves,segs:lines+curves,width:Number(stroke?.lineWidth||0),rgb,closed,chordNorm:chord/d,lengthNorm:plen/d})}};let dev=null;try{dev=new mupdf.Device(cb);page.run(dev,mupdf.Matrix.identity)}finally{try{dev?.close?.()}catch(_){}try{dev?.destroy?.()}catch(_){}}return out.filter(x=>x.segs>0)}
function similar(x,s){if(colorDist(x.rgb,s.rgb)>.028)return false;const wt=Math.max(.045,Math.abs(s.width)*.16);if(Math.abs(x.width-s.width)>wt)return false;if((x.curves>0)!==(s.curves>0)||(x.lines>0)!==(s.lines>0))return false;if(!!x.closed!==!!s.closed)return false;const sw=Math.max(.001,Math.abs(s.bbox[2]-s.bbox[0])),sh=Math.max(.001,Math.abs(s.bbox[3]-s.bbox[1])),xw=Math.max(.001,Math.abs(x.bbox[2]-x.bbox[0])),xh=Math.max(.001,Math.abs(x.bbox[3]-x.bbox[1])),ds=Math.hypot(sw,sh),dx=Math.hypot(xw,xh);if(ds>0&&(dx/ds<.72||dx/ds>1.39))return false;const sar=sw/sh,xar=xw/xh;if(Math.max(sar,xar)/Math.max(.001,Math.min(sar,xar))>1.32)return false;const curveRatioS=s.curves/Math.max(1,s.segs),curveRatioX=x.curves/Math.max(1,x.segs);if(Math.abs(curveRatioX-curveRatioS)>.14)return false;if(!s.closed&&Math.abs((x.chordNorm||0)-(s.chordNorm||0))>.16)return false;if(Math.abs((x.lengthNorm||0)-(s.lengthNorm||0))>.38)return false;const tol=Math.max(1,Math.ceil(s.segs*.20));return Math.abs(x.segs-s.segs)<=tol}
'''
p.write_text(s[:a]+new+s[b:])
print('shape signature filter applied')
