from pathlib import Path
p=Path('selector-nubes-multistream-core.html')
s=p.read_text(encoding='utf-8')
start=s.index('function directRefIdentity(')
end=s.index('function remapStructTargets',start)
new=r'''async function directTextDigest(text){const d=await crypto.subtle.digest('SHA-256',raw(text));return Array.from(new Uint8Array(d),x=>x.toString(16).padStart(2,'0')).join('')}
function directLocatorIndex(allStrokes){const idx=new Map(),roots=model?.refs||[];for(let i=0;i<roots.length;i++)idx.set(deepKey(roots[i]),{root:i,names:[]});for(const s of allStrokes||[]){const invs=Array.isArray(s?.invocations)?s.invocations:[];if(!invs.length)continue;let loc=idx.get(deepKey(invs[0].parentRef));if(!loc)continue;for(const inv of invs){const knownParent=idx.get(deepKey(inv.parentRef));if(knownParent)loc=knownParent;const name=String(inv.name||'').replace(/^\//,'');if(!name)break;const child={root:loc.root,names:[...loc.names,name]};idx.set(deepKey(inv.formRef),child);loc=child}}return idx}
function directResolveStream(page,loc){if(!loc||!Number.isInteger(loc.root))throw new Error('localizador estructural directo inválido');const roots=refs(page);let ref=roots[loc.root];if(!ref?.isStream?.())throw new Error('el stream raíz P'+loc.root+' no existe en la copia directa');let res=deepPageResources(page.getObject());for(const rawName of loc.names||[]){const name=String(rawName||'').replace(/^\//,'');const xd=deepObj(deepObj(res)?.get?.('XObject'));if(!xd?.isDictionary?.())throw new Error('no existe XObject para /'+name+' en la ruta estructural directa');const next=xd.get(name);if(!next?.isStream?.())throw new Error('/'+name+' ya no es un stream en la ruta estructural directa');const dict=deepObj(next);if(deepName(dict?.get?.('Subtype'))!=='Form')throw new Error('/'+name+' ya no es un Form en la ruta estructural directa');ref=next;res=deepResources(dict,res)}return ref}
async function makeDirectEditPlan(targets,allStrokes){const selectedBySource=new Map(),allBySourceCount=new Map();for(const t of targets||[])selectedBySource.set(t.sourceKey,(selectedBySource.get(t.sourceKey)||0)+1);for(const q of allStrokes||[])allBySourceCount.set(q.sourceKey,(allBySourceCount.get(q.sourceKey)||0)+1);for(const[k,n]of selectedBySource)if(n!==(allBySourceCount.get(k)||0))throw new Error('XObject compartido: la transacción directa afectaría geometría no azul');const groups=strokeEditGroups(targets),locators=directLocatorIndex(allStrokes),plan=[];for(const g of groups.values()){const locator=locators.get(g.key);if(!locator)throw new Error('no pude construir una ruta estructural estable para el stream seleccionado');const text=latin(g.ref.readStream()),ranges=[];for(const[a,b]of g.ranges){if(a<0||b>text.length||a>=b)throw new Error('rango directo inválido en '+g.key);ranges.push({start:a,end:b,original:text.slice(a,b)})}plan.push({locator,length:text.length,digest:await directTextDigest(text),ranges})}if(!plan.length)throw new Error('la transacción directa no encontró streams editables');return plan}
async function applyDirectEditPlan(work,plan){let touched=0,page=null;try{page=work.loadPage(0);for(const g of plan){const ref=directResolveStream(page,g.locator);let text=latin(ref.readStream());if(text.length!==g.length)throw new Error('el stream localizado estructuralmente cambió de longitud antes de la transacción directa');if(await directTextDigest(text)!==g.digest)throw new Error('la huella SHA-256 del stream localizado no coincide con la copia base');for(const r of g.ranges){if(r.start<0||r.end>text.length||r.start>=r.end||text.slice(r.start,r.end)!==r.original)throw new Error('el contenido del rango seleccionado no coincide con la identidad estructural esperada');text=text.slice(0,r.start)+text.slice(r.end)}ref.writeStream(raw(text));touched++}return touched}finally{try{page?.destroy?.()}catch(_){}}}
'''
s=s[:start]+new+s[end:]
old='const touched=applyDirectEditPlan(work,plan);'
assert old in s, 'apply direct call not found'
s=s.replace(old,'const touched=await applyDirectEditPlan(work,plan);',1)
old="const directPlan=makeDirectEditPlan(structSelected,model.strokes),ok=await attemptSingleTransaction(directPlan,'incremental');"
assert old in s, 'make direct plan call not found'
s=s.replace(old,"const directPlan=await makeDirectEditPlan(structSelected,model.strokes),ok=await attemptSingleTransaction(directPlan,'incremental');",1)
p.write_text(s,encoding='utf-8')
print('stable locator patch applied',len(s))
