from pathlib import Path

src=Path('selector-nubes-causal-ap-profundo-core.html').read_text()

src=src.replace('<title>Selector de nubes · causal exacto /AP profundo</title>','<title>Selector de nubes · causal exacto por streams globales</title>',1)

needle="""function appearancePaintRanges(text){
 const out=[];let i=0,args=[],pathStart=null;const nums=()=>args.filter(x=>x.type==='num'),clear=()=>{args=[]};while(i<text.length){const t=nextToken(text,i);if(!t)break;i=t.next;if(t.type==='num'||t.type==='name'){args.push(t);continue}if(t.type!=='op')continue;const op=t.value,na=nums();if(op==='m'&&na.length>=2){if(pathStart==null)pathStart=na[na.length-2].start;clear();continue}if(op==='re'&&na.length>=4){if(pathStart==null)pathStart=na[na.length-4].start;clear();continue}if(op==='l'||op==='c'||op==='v'||op==='y'||op==='h'){clear();continue}if(op==='S'||op==='s'||op==='B'||op==='B*'||op==='b'||op==='b*'){if(pathStart!=null)out.push({start:pathStart,end:t.end,op});pathStart=null;clear();continue}if(op==='n'||op==='f'||op==='F'||op==='f*'){pathStart=null;clear();continue}clear()}return out
}
"""
insert=needle+"""function externalCommandRanges(text){
 const out=[...appearancePaintRanges(text)];let i=0,cmdStart=null;while(i<text.length){const t=nextToken(text,i);if(!t)break;i=t.next;if(cmdStart==null)cmdStart=t.start;if(t.type!=='op')continue;const op=t.value;if(op==='Tj'||op==='TJ'||op==="'"||op==='\"'||op==='Do')out.push({start:cmdStart,end:t.end,op});cmdStart=null}const seen=new Set(),uniq=[];for(const r of out.sort((a,b)=>a.start-b.start||a.end-b.end)){const k=r.start+'|'+r.end;if(seen.has(k))continue;seen.add(k);uniq.push(r)}return uniq
}
function allPdfStreams(pdf){
 const out=[];let n=0;try{n=Number(pdf.countObjects?.()||0)}catch(_){}for(let i=1;i<n;i++){try{const q=deepObj(pdf.newIndirect(i));if(q?.isStream?.())out.push({num:i,ref:q,key:String(i)})}catch(_){}}return out
}
"""
if needle not in src: raise SystemExit('appearancePaintRanges needle not found')
src=src.replace(needle,insert,1)

needle2="""  causalDiagnostic='pool inicial='+pool.length+' · pruebas únicas totales='+tested+' · ampliadas únicas='+expanded+' · operadores 1:1='+oneToOne+' · anotaciones='+annotationCount+' · widgets='+widgetCount+' · anotaciones probadas='+annotationTests+' · widgets intentados='+widgetAttempts+' · widgets probados='+widgetTests+' · errores widget='+widgetErrors+(lastWidgetError?' · último error widget='+lastWidgetError:'')+' · AP streams='+apStreams+' · AP forms='+apForms+' · AP operadores='+apOperators+' · AP pruebas='+apTests+' · AP errores='+apErrors+(lastApError?' · último error AP='+lastApError:'')+' · cubiertos='+(selectedVisual-missingCount)+'/'+selectedVisual;
  if(!missingCount&&(annotationPlans.length||widgetPlans.length||widgetAppearanceOps.length)){const structKeys=chosen.map(i=>structStableKey(cm.strokes[i]));if(chosen.length+annotationPlans.length+widgetPlans.length+widgetAppearanceOps.length!==selectedVisual||new Set(structKeys).size!==structKeys.length)throw new Error('la ruta híbrida no quedó 1:1');return{kind:'hybrid',structRoute:chosen,structKeys,annotations:annotationPlans,widgets:widgetPlans,widgetAppearanceOps}}
  if(missingCount)throw new Error('faltan fuentes causales para '+missingCount+' trazo(s) azul(es) después de probar operadores, anotaciones, widgets y operadores internos de /AP · '+causalDiagnostic);
"""
replacement2="""  const globalStreamOps=[];let globalStreams=0,globalStreamTests=0,globalCommandCandidates=0,globalCommandTests=0,globalStreamErrors=0,lastGlobalStreamError='';
  if(missingCount){
   let enumDoc=null;try{enumDoc=mupdf.PDFDocument.openDocument(outBase,'application/pdf');const streams=allPdfStreams(enumDoc),known=new Set(cm.strokes.map(s=>{try{return deepKey(s.sourceRef)}catch(_){return''}}));const candidates=streams.filter(s=>!known.has(deepKey(s.ref)));globalStreams=candidates.length;for(let ci=0;ci<candidates.length&&missingCount;ci++){
    const objNum=candidates[ci].num;let td=null,tp=null;try{td=mupdf.PDFDocument.openDocument(outBase,'application/pdf');tp=td.loadPage(0);const ref=deepObj(td.newIndirect(objNum));if(!ref?.isStream?.())continue;const original=latin(ref.readStream());ref.writeStream(raw(''));try{tp?.destroy?.()}catch(_){}tp=td.loadPage(0);const av=collectVisual(tp),ab=new Map();for(const v of av){const k=sig(v);ab.set(k,(ab.get(k)||0)+1)}let removed=[],added=0;for(const[k,n]of baseBag){const d=Math.max(0,n-(ab.get(k)||0));for(let q=0;q<d;q++)removed.push(k)}for(const[k,n]of ab)added+=Math.max(0,n-(baseBag.get(k)||0));globalStreamTests++;const missingHit=removed.some(k=>(missing.get(k)||0)>0);if(missingHit&&added===0){
      if(removed.length===1){const k=removed[0],left=missing.get(k)||0;if(left>0){globalStreamOps.push({objNum,mode:'whole',start:0,end:original.length,op:'STREAM',sig:k});if(left===1)missing.delete(k);else missing.set(k,left-1);missingCount--;}}
      else{const ranges=externalCommandRanges(original);globalCommandCandidates+=ranges.length;for(let ri=0;ri<ranges.length&&missingCount;ri++){let xd=null,xp=null;try{xd=mupdf.PDFDocument.openDocument(outBase,'application/pdf');xp=xd.loadPage(0);const xr=deepObj(xd.newIndirect(objNum));if(!xr?.isStream?.())continue;const text=latin(xr.readStream()),rr=ranges[ri];if(rr.end>text.length||rr.start<0||rr.start>=rr.end)continue;xr.writeStream(raw(text.slice(0,rr.start)+text.slice(rr.end)));try{xp?.destroy?.()}catch(_){}xp=xd.loadPage(0);const xv=collectVisual(xp),xb=new Map();for(const v of xv){const k=sig(v);xb.set(k,(xb.get(k)||0)+1)}let rmd=[],add=0;for(const[k,n]of baseBag){const d=Math.max(0,n-(xb.get(k)||0));for(let q=0;q<d;q++)rmd.push(k)}for(const[k,n]of xb)add+=Math.max(0,n-(baseBag.get(k)||0));globalCommandTests++;if(rmd.length===1&&add===0){const k=rmd[0],left=missing.get(k)||0;if(left>0){globalStreamOps.push({objNum,mode:'range',start:rr.start,end:rr.end,op:rr.op,sig:k});if(left===1)missing.delete(k);else missing.set(k,left-1);missingCount--;break}}}catch(e){globalStreamErrors++;lastGlobalStreamError=String(e?.message||e)}finally{try{xp?.destroy?.()}catch(_){}try{xd?.destroy?.()}catch(_){}}if((globalCommandTests%8)===0){status.textContent='Buscando fuente visual fuera del modelo · comando '+globalCommandTests+'…';await uiYield()}}}
     }
    }catch(e){globalStreamErrors++;lastGlobalStreamError=String(e?.message||e)}finally{try{tp?.destroy?.()}catch(_){}try{td?.destroy?.()}catch(_){}}if((globalStreamTests%8)===0){status.textContent='Buscando fuente visual fuera del modelo · stream '+globalStreamTests+'/'+globalStreams+'…';await uiYield()}}
   }}finally{try{enumDoc?.destroy?.()}catch(_){}}
  }
  causalDiagnostic='pool inicial='+pool.length+' · pruebas únicas totales='+tested+' · ampliadas únicas='+expanded+' · operadores 1:1='+oneToOne+' · anotaciones='+annotationCount+' · widgets='+widgetCount+' · anotaciones probadas='+annotationTests+' · widgets intentados='+widgetAttempts+' · widgets probados='+widgetTests+' · errores widget='+widgetErrors+(lastWidgetError?' · último error widget='+lastWidgetError:'')+' · AP streams='+apStreams+' · AP forms='+apForms+' · AP operadores='+apOperators+' · AP pruebas='+apTests+' · AP errores='+apErrors+(lastApError?' · último error AP='+lastApError:'')+' · streams globales='+globalStreams+' · streams probados='+globalStreamTests+' · comandos candidatos='+globalCommandCandidates+' · comandos probados='+globalCommandTests+' · errores streams='+globalStreamErrors+(lastGlobalStreamError?' · último error stream='+lastGlobalStreamError:'')+' · cubiertos='+(selectedVisual-missingCount)+'/'+selectedVisual;
  if(!missingCount&&(annotationPlans.length||widgetPlans.length||widgetAppearanceOps.length||globalStreamOps.length)){const structKeys=chosen.map(i=>structStableKey(cm.strokes[i]));if(chosen.length+annotationPlans.length+widgetPlans.length+widgetAppearanceOps.length+globalStreamOps.length!==selectedVisual||new Set(structKeys).size!==structKeys.length)throw new Error('la ruta híbrida no quedó 1:1');return{kind:'hybrid',structRoute:chosen,structKeys,annotations:annotationPlans,widgets:widgetPlans,widgetAppearanceOps,globalStreamOps}}
  if(missingCount)throw new Error('falta '+missingCount+' trazo(s) azul(es) después de probar operadores y todos los streams PDF causales disponibles · '+causalDiagnostic);
"""
if needle2 not in src: raise SystemExit('causal diagnostic needle not found')
src=src.replace(needle2,replacement2,1)

needle3="""for(const xp of (plan.widgetAppearanceOps||[])){const widgets=wp.getWidgets?.()||[],w=widgets[xp.widgetIndex];if(!w)throw new Error('el widget de apariencia causal no pudo localizarse');const aps=widgetAppearanceStreams(w),ap=aps[xp.appearanceIndex];if(!ap)throw new Error('la apariencia /AP causal no pudo localizarse');const targets=deepAppearanceTargets(ap.ref),target=targets.find(t=>t.streamKey===xp.streamKey&&t.start===xp.start&&t.end===xp.end);if(!target)throw new Error('el operador /AP profundo causal no pudo localizarse');let text=latin(target.ref.readStream());text=text.slice(0,target.start)+text.slice(target.end);target.ref.writeStream(raw(text));}try{wp?.destroy?.()}catch(_){}wp=work.loadPage(0);"""
replacement3="""for(const xp of (plan.widgetAppearanceOps||[])){const widgets=wp.getWidgets?.()||[],w=widgets[xp.widgetIndex];if(!w)throw new Error('el widget de apariencia causal no pudo localizarse');const aps=widgetAppearanceStreams(w),ap=aps[xp.appearanceIndex];if(!ap)throw new Error('la apariencia /AP causal no pudo localizarse');const targets=deepAppearanceTargets(ap.ref),target=targets.find(t=>t.streamKey===xp.streamKey&&t.start===xp.start&&t.end===xp.end);if(!target)throw new Error('el operador /AP profundo causal no pudo localizarse');let text=latin(target.ref.readStream());text=text.slice(0,target.start)+text.slice(target.end);target.ref.writeStream(raw(text));}for(const gp of (plan.globalStreamOps||[])){const ref=deepObj(work.newIndirect(gp.objNum));if(!ref?.isStream?.())throw new Error('el stream causal global '+gp.objNum+' ya no es un stream');let text=latin(ref.readStream());if(gp.mode==='whole')ref.writeStream(raw(''));else{if(gp.start<0||gp.end>text.length||gp.start>=gp.end)throw new Error('el rango causal global quedó fuera de límites');ref.writeStream(raw(text.slice(0,gp.start)+text.slice(gp.end)))}}try{wp?.destroy?.()}catch(_){}wp=work.loadPage(0);"""
if needle3 not in src: raise SystemExit('attemptHybrid insertion needle not found')
src=src.replace(needle3,replacement3,1)

needle4="""return{out,touched:byRef.size+(plan.annotations||[]).length+(plan.widgets||[]).length+(plan.widgetAppearanceOps||[]).length,number,saveMode:saveMode||'reescritura mínima'}"""
replacement4="""return{out,touched:byRef.size+(plan.annotations||[]).length+(plan.widgets||[]).length+(plan.widgetAppearanceOps||[]).length+(plan.globalStreamOps||[]).length,number,saveMode:saveMode||'reescritura mínima'}"""
if needle4 not in src: raise SystemExit('touched needle not found')
src=src.replace(needle4,replacement4,1)

Path('selector-nubes-causal-streams-core.html').write_text(src)
wrap=Path('selector-nubes-causal-ap-profundo.html').read_text()
wrap=wrap.replace('Selector de nubes · causal exacto /AP profundo','Selector de nubes · causal exacto por streams globales',1)
wrap=wrap.replace('./selector-nubes-causal-ap-profundo-core.html?v=20260903-apdeep1','./selector-nubes-causal-streams-core.html?v=20260903-streamcausal1',1)
Path('selector-nubes-causal-streams.html').write_text(wrap)
