from pathlib import Path
p=Path('selector-nubes-multistream-core.html')
s=p.read_text()
start=s.index('function chooseClassic(e){')
end=s.index('\nconst r3=', start)
new=r'''function seedCompat(x,s){if(colorDist(x.rgb,s.rgb)>.035)return false;const wt=Math.max(.06,Math.abs(s.width)*.22);if(Math.abs(x.width-s.width)>wt)return false;if((x.curves>0)!==(s.curves>0)||(x.lines>0)!==(s.lines>0))return false;if(!!x.closed!==!!s.closed)return false;const ds=Math.max(.001,diag(s.bbox)),dx=Math.max(.001,diag(x.bbox));if(dx/ds<.5||dx/ds>2)return false;const tol=Math.max(2,Math.ceil(s.segs*.45));return Math.abs(x.segs-s.segs)<=tol}
function seedComponentGroups(items){if(!items.length)return[];const md=med(items.map(x=>diag(x.bbox)).filter(Boolean)),tol=Math.max(.45,md*.24),p=items.map((_,i)=>i),f=i=>p[i]===i?i:(p[i]=f(p[i])),u=(i,j)=>{i=f(i);j=f(j);if(i!==j)p[j]=i};for(let i=0;i<items.length;i++)for(let j=i+1;j<items.length;j++){const A=[items[i].first,items[i].last].filter(Boolean),B=[items[j].first,items[j].last].filter(Boolean);if(A.some(a=>B.some(b=>Math.hypot(a[0]-b[0],a[1]-b[1])<=tol)))u(i,j)}const m=new Map();for(let i=0;i<items.length;i++){const k=f(i);if(!m.has(k))m.set(k,[]);m.get(k).push(items[i])}return[...m.values()]}
function componentBox(a){return[Math.min(...a.map(x=>x.bbox[0])),Math.min(...a.map(x=>x.bbox[1])),Math.max(...a.map(x=>x.bbox[2])),Math.max(...a.map(x=>x.bbox[3]))]}
function componentLike(a,b){if(!a.length||!b.length)return false;const nr=a.length/b.length;if(nr<.42||nr>2.4)return false;const da=Math.max(.001,diag(componentBox(a))),db=Math.max(.001,diag(componentBox(b))),dr=da/db;if(dr<.38||dr>2.65)return false;const ma=med(a.map(x=>diag(x.bbox)).filter(Boolean)),mb=med(b.map(x=>diag(x.bbox)).filter(Boolean));if(ma&&mb){const r=ma/mb;if(r<.62||r>1.62)return false}return true}
function chooseClassic(e){if(!classicVisual.length){status.textContent='MuPDF no entregó trazos visuales para esta página.';return}const add=!!(e.ctrlKey||e.shiftKey),prevVisual=add?visualSelected.slice():[],prevFamilies=add?selectionFamilies:0,r=viewport.getBoundingClientRect(),sx=e.clientX-r.left,sy=e.clientY-r.top,bx=(sx-panX)/zoom,by=(sy-panY)/zoom,x=pageBounds[0]+bx/baseRs,y=pageBounds[1]+by/baseRs;let best=null,bd=Infinity;const pad=15/Math.max(.1,baseRs*zoom);for(const s of classicVisual){if(x<s.bbox[0]-pad||x>s.bbox[2]+pad||y<s.bbox[1]-pad||y>s.bbox[3]+pad)continue;const d=distance(s,x,y);if(d<bd){bd=d;best=s}}const tol=14/Math.max(.1,baseRs*zoom);if(!best||bd>tol){status.textContent='No encontré un trazo visual suficientemente cerca.';return}const broad=classicVisual.filter(v=>seedCompat(v,best)),groups=seedComponentGroups(broad),seed=groups.find(g=>g.includes(best))||[best];let famVisual=[];if(seed.length>=3){for(const g of groups)if(g===seed||componentLike(g,seed))famVisual.push(...g)}else{famVisual=classicVisual.filter(v=>similar(v,best))}famVisual=[...new Set(famVisual)];const newVisual=famVisual.filter(v=>!prevVisual.includes(v));visualSelected=add?[...new Set([...prevVisual,...famVisual])]:famVisual;visualSelected.sort((a,b)=>a._ordinal-b._ordinal);selectionFamilies=add?(prevFamilies+(newVisual.length?1:0)):1;structSelected=[];selectionAlternatives=[];selectionMapSafe=false;drawSelection();setButtons();const vg=components(visualSelected);status.textContent='Selección acumulada · familias='+selectionFamilies+' · resaltados='+visualSelected.length+' · grupos≈'+vg+' · expansión por componente · azul listo · correspondencia estructural se calculará al pulsar Eliminar · Ctrl/Shift+clic añade otro tipo'}'''
s=s[:start]+new+s[end:]
p.write_text(s)
print('patched component seed expansion')
