import * as mupdf from 'https://cdn.jsdelivr.net/npm/mupdf@1.28.0/dist/mupdf.js';
let workerPromise;
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[‐‑‒–—−]/g,'-').replace(/\s+/g,' ').trim().toLowerCase();
const canonical=s=>norm(s).replace(/\s*[-]\s*/g,'-').replace(/\s*([:/_.])\s*/g,'$1');
const key=s=>canonical(s).replace(/[^a-z0-9]/g,'').replace(/o/g,'0').replace(/[il]/g,'1');
function lev(a,b){const p=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let q=[i];for(let j=1;j<=b.length;j++)q[j]=Math.min(q[j-1]+1,p[j]+1,p[j-1]+(a[i-1]===b[j-1]?0:1));for(let j=0;j<q.length;j++)p[j]=q[j]}return p[b.length]}
function sim(a,b){return a&&b?1-lev(a,b)/Math.max(a.length,b.length):0}
function iou(a,b){const x=Math.max(0,Math.min(a[2],b[2])-Math.max(a[0],b[0])),y=Math.max(0,Math.min(a[3],b[3])-Math.max(a[1],b[1]));const inter=x*y,aa=Math.max(1,(a[2]-a[0])*(a[3]-a[1])),bb=Math.max(1,(b[2]-b[0])*(b[3]-b[1]));return inter/(aa+bb-inter)}
async function worker(){if(workerPromise)return workerPromise;workerPromise=import('https://esm.sh/tesseract.js@5.1.0').then(({createWorker})=>createWorker('spa+eng')).then(async w=>{try{await w.setParameters({preserve_interword_spaces:'1',user_defined_dpi:'300',tessedit_pageseg_mode:'11'})}catch(_){}return w}).catch(e=>{workerPromise=null;throw e});return workerPromise}
async function recognize(canvas,mode){const w=await worker();await w.setParameters({preserve_interword_spaces:'1',user_defined_dpi:'300',tessedit_pageseg_mode:String(mode)});return (await w.recognize(canvas))?.data||null}
function words(data){return (data?.words||[]).filter(w=>w?.text?.trim()&&w.bbox).sort((a,b)=>{const ay=(a.bbox.y0+a.bbox.y1)/2,by=(b.bbox.y0+b.bbox.y1)/2;const h=Math.max(1,(a.bbox.y1-a.bbox.y0+(b.bbox.y1-b.bbox.y0))/2);return Math.abs(ay-by)<Math.max(5,h*.8)?a.bbox.x0-b.bbox.x0:ay-by})}
function union(ws){let b=null;for(const w of ws){const q=w?.bbox;if(!q)continue;b=b?[Math.min(b[0],q.x0),Math.min(b[1],q.y0),Math.max(b[2],q.x1),Math.max(b[3],q.y1)]:[q.x0,q.y0,q.x1,q.y1]}return b}
function result(box,conf,text,target,scale,ox,oy){const b=box.map((v,i)=>(v+(i<2?(i===0?ox:oy):i===2?ox:oy))/scale);const k=key(text),t=key(target);return {bbox:b,confidence:Number(conf)||50,similarity:sim(k,t),ocrText:text,exact:k===t}}
function findLine(data,target,scale,ox,oy){const t=key(target),out=[];for(const line of data?.lines||[]){const txt=String(line.text||'').trim();if(!txt)continue;const k=key(txt),ratio=Math.min(k.length,t.length)/Math.max(k.length,t.length),exact=k===t,ok=exact||(ratio>=.72&&sim(k,t)>=.82);if(ok&&line.bbox){out.push(result([line.bbox.x0,line.bbox.y0,line.bbox.x1,line.bbox.y1],line.confidence,txt,target,scale,ox,oy))}}return out}
function findWords(data,target,scale,ox,oy){const t=key(target),ws=words(data),out=[];for(let i=0;i<ws.length;i++){let s='',pick=[];for(let j=i;j<Math.min(ws.length,i+50);j++){s+=(s?' ':'')+ws[j].text;pick.push(ws[j]);const k=key(s),ratio=Math.min(k.length,t.length)/Math.max(k.length,t.length),exact=k===t,ok=exact||(ratio>=.72&&sim(k,t)>=.84);if(ok){const conf=Math.min(...pick.map(x=>Number(x.confidence)||50));if(exact||conf>=35){const b=union(pick);if(b)out.push(result(b,conf,s,target,scale,ox,oy));break}}if(k.length>t.length+55)break}}return out}
function find(data,target,scale=1,ox=0,oy=0){const a=[...findLine(data,target,scale,ox,oy),...findWords(data,target,scale,ox,oy)];const out=[];for(const m of a){const same=out.find(x=>iou(x.bbox,m.bbox)>.55);if(same){if(m.exact&&!same.exact||m.confidence>same.confidence)Object.assign(same,m)}else out.push(m)}return out}
function anchors(target){return [...new Set(String(target).split(/[_\-\s./:]+/).map(x=>x.trim()).filter(x=>x.length>=3).map(key))].sort((a,b)=>b.length-a.length).slice(0,5)}
function anchorWords(data,target){const ws=words(data),as=anchors(target),out=[];for(const a of as){let best=null;for(const w of ws){const k=key(w.text),s=sim(k,a);if(k===a||s>=.82){if(!best||s>best.score)best={word:w,score:s}}}if(best)out.push(best)}return out}
function crop(bitmap,b,padX,padY){const x=Math.max(0,Math.floor(b.x0-padX)),y=Math.max(0,Math.floor(b.y0-padY)),x2=Math.min(bitmap.width,Math.ceil(b.x1+padX)),y2=Math.min(bitmap.height,Math.ceil(b.y1+padY));const c=document.createElement('canvas');c.width=Math.max(1,x2-x);c.height=Math.max(1,y2-y);c.getContext('2d').drawImage(bitmap,x,y,c.width,c.height,0,0,c.width,c.height);return {c,x,y}}
async function anchorPass(bitmap,target,baseData){const hits=[];for(const a of anchorWords(baseData,target)){const b=a.word.bbox,padX=Math.max(300,(b.x1-b.x0)*14),padY=Math.max(120,(b.y1-b.y0)*7),q=crop(bitmap,b,padX,padY);for(const mode of [6,11]){const d=await recognize(q.c,mode);hits.push(...find(d,target,3,q.x,q.y));if(hits.some(x=>x.exact))return hits}}return hits}
function gray(bitmap){const c=document.createElement('canvas');c.width=bitmap.width;c.height=bitmap.height;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(bitmap,0,0);const im=x.getImageData(0,0,c.width,c.height),d=im.data;for(let i=0;i<d.length;i+=4){const y=Math.round(.299*d[i]+.587*d[i+1]+.114*d[i+2]);const v=Math.max(0,Math.min(255,Math.round((y-128)*1.35+128)));d[i]=d[i+1]=d[i+2]=v}x.putImageData(im,0,0);return c}
async function pageOCR(page,target){const scale=3,pix=page.toPixmap(mupdf.Matrix.scale(scale,scale),mupdf.ColorSpace.DeviceRGB,false,false),bitmap=await createImageBitmap(new Blob([pix.asPNG()],{type:'image/png'}));try{for(const mode of [11,6]){const data=await recognize(bitmap,mode);let hits=find(data,target,scale,0,0);if(hits.length)return hits;const ah=await anchorPass(bitmap,target,data);if(ah.length)return ah}const g=gray(bitmap);for(const mode of [11,6]){const data=await recognize(g,mode);const hits=find(data,target,scale,0,0);if(hits.length)return hits}const cols=2,rows=2,tw=Math.ceil(bitmap.width/cols),th=Math.ceil(bitmap.height/rows),all=[];for(let ry=0;ry<rows;ry++)for(let cx=0;cx<cols;cx++){const x=Math.max(0,Math.floor(cx*tw-tw*.18)),y=Math.max(0,Math.floor(ry*th-th*.18)),x2=Math.min(bitmap.width,Math.ceil((cx+1)*tw+tw*.18)),y2=Math.min(bitmap.height,Math.ceil((ry+1)*th+th*.18)),c=document.createElement('canvas');c.width=x2-x;c.height=y2-y;c.getContext('2d').drawImage(bitmap,x,y,c.width,c.height,0,0,c.width,c.height);for(const mode of [11,6]){const d=await recognize(c,mode);const hits=find(d,target,scale,x,y);all.push(...hits);if(hits.some(h=>h.exact))return hits}}return all}finally{bitmap.close?.()}}
export async function runRecognition(){const batch=window.__batchAnalysis;if(!Array.isArray(batch)||!batch.length)return{total:0};const status=document.querySelector('#batchStatus'),summary=document.querySelector('#batchSummary');let total=0;for(let ai=0;ai<batch.length;ai++){const a=batch[ai];if(!a||a.error||!a.data)continue;const doc=mupdf.PDFDocument.openDocument(a.data,'application/pdf');try{for(let pi=0;pi<doc.countPages();pi++){if(status)status.textContent=`Reconociendo vector/OCR · ${ai+1}/${batch.length} · página ${pi+1} · ${a.name}`;if(a.kinds?.vector!==true)continue;const page=doc.loadPage(pi);for(const c of a.counts||[]){if(!c.find?.trim()||c.count>0||c.annotationCount>0)continue;const matches=await pageOCR(page,c.find);if(!matches.length)continue;c.ocrCount=(c.ocrCount||0)+matches.length;c.ocrMatches=(c.ocrMatches||[]).concat(matches.map(m=>({...m,page:pi+1})));c.pages=c.pages||[];if(!c.pages.includes(pi+1))c.pages.push(pi+1);total+=matches.length}}}finally{doc.destroy()}}if(summary){summary.textContent=summary.textContent.replace(/ · \d+ coincidencias? vectorial(?:es)?\/OCR · ningún archivo modificado/,'')+` · ${total} coincidencia${total===1?'':'s'} vectorial/OCR · ningún archivo modificado`;summary.classList.remove('hidden')}if(status)status.textContent=total?`Reconocimiento terminado: ${total} coincidencia${total===1?'':'s'} vectorial/OCR detectada${total===1?'':'s'}. No se ha modificado ningún PDF.`:'Sin coincidencias vectoriales/OCR.';return{total}}
