import * as mupdf from 'https://cdn.jsdelivr.net/npm/mupdf@1.28.0/dist/mupdf.js';
let workerPromise=null;
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[‐‑‒–—−]/g,'-').replace(/\s+/g,' ').trim().toLowerCase();
const canonical=s=>norm(s).replace(/\s*[-]\s*/g,'-').replace(/\s*([:/_.])\s*/g,'$1');
const key=s=>canonical(s).replace(/[^a-z0-9]/g,'').replace(/o/g,'0').replace(/[il]/g,'1');
const lev=(a,b)=>{if(a===b)return 0;let p=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){const q=[i];for(let j=1;j<=b.length;j++)q[j]=Math.min(q[j-1]+1,p[j]+1,p[j-1]+(a[i-1]===b[j-1]?0:1));p=q}return p[b.length]};
const sim=(a,b)=>a&&b?1-lev(a,b)/Math.max(a.length,b.length):0;
const iou=(a,b)=>{const x=Math.max(0,Math.min(a[2],b[2])-Math.max(a[0],b[0])),y=Math.max(0,Math.min(a[3],b[3])-Math.max(a[1],b[1])),z=x*y;return z/(Math.max(1,(a[2]-a[0])*(a[3]-a[1]))+Math.max(1,(b[2]-b[0])*(b[3]-b[1]))-z)};
async function worker(){if(workerPromise)return workerPromise;workerPromise=(async()=>{const {createWorker}=await import('https://esm.sh/tesseract.js@5.1.0');const w=await createWorker('eng');await w.setParameters({preserve_interword_spaces:'1',user_defined_dpi:'140',tessedit_pageseg_mode:'11'});return w})().catch(e=>{workerPromise=null;throw e});return workerPromise}
async function recognize(bitmap,mode='11',timeoutMs=20000){const w=await worker();await w.setParameters({tessedit_pageseg_mode:String(mode),preserve_interword_spaces:'1',user_defined_dpi:'140'});let timer;try{return await Promise.race([w.recognize(bitmap).then(r=>r?.data||null),new Promise((_,rej)=>{timer=setTimeout(()=>rej(new Error('OCR timeout (20 s)')),timeoutMs)})])}finally{clearTimeout(timer)}}
function ordered(data){return (data?.words||[]).filter(w=>w?.text?.trim()&&w.bbox).sort((a,b)=>{const ay=(a.bbox.y0+a.bbox.y1)/2,by=(b.bbox.y0+b.bbox.y1)/2,h=Math.max(8,((a.bbox.y1-a.bbox.y0)+(b.bbox.y1-b.bbox.y0))/2);return Math.abs(ay-by)<h*.8?a.bbox.x0-b.bbox.x0:ay-by})}
function union(ws){return ws.reduce((b,w)=>{const q=w.bbox;return b?[Math.min(b[0],q.x0),Math.min(b[1],q.y0),Math.max(b[2],q.x1),Math.max(b[3],q.y1)]:[q.x0,q.y0,q.x1,q.y1]},null)}
function makeMatch(box,confidence,text,target,scale,ox=0,oy=0){const k=key(text),t=key(target);return{bbox:[(box[0]+ox)/scale,(box[1]+oy)/scale,(box[2]+ox)/scale,(box[3]+oy)/scale],confidence:Number(confidence)||50,similarity:sim(k,t),ocrText:text,exact:k===t}}
function findOne(data,target,scale,ox=0,oy=0){const t=key(target),out=[];if(!t)return out;
  for(const line of data?.lines||[]){const txt=String(line.text||'').trim();if(!txt||!line.bbox)continue;const k=key(txt),ratio=Math.min(k.length,t.length)/Math.max(k.length,t.length);if(k===t||(ratio>=.84&&sim(k,t)>=.90))out.push(makeMatch([line.bbox.x0,line.bbox.y0,line.bbox.x1,line.bbox.y1],line.confidence,txt,target,scale,ox,oy))}
  const ws=ordered(data);for(let i=0;i<ws.length;i++){let s='',pick=[];for(let j=i;j<Math.min(ws.length,i+36);j++){pick.push(ws[j]);s+=(s?' ':'')+ws[j].text;const k=key(s),ratio=Math.min(k.length,t.length)/Math.max(k.length,t.length),exact=k===t;if(exact||(ratio>=.80&&sim(k,t)>=.86)){const b=union(pick),conf=Math.min(...pick.map(w=>Number(w.confidence)||50));if(b&&(exact||conf>=40))out.push(makeMatch(b,conf,s,target,scale,ox,oy));break}if(k.length>t.length+50)break}}
  const uniq=[];for(const m of out){const same=uniq.find(x=>iou(x.bbox,m.bbox)>.55);if(!same)uniq.push(m);else if(m.exact||m.confidence>same.confidence)Object.assign(same,m)}return uniq}
function matchAll(data,targets,scale,ox=0,oy=0){const out=new Map(targets.map(t=>[t,findOne(data,t,scale,ox,oy)]));return out}
function render(page,maxDim){const b=page.getBounds?.()||[0,0,1000,1000],w=Math.max(1,b[2]-b[0]),h=Math.max(1,b[3]-b[1]);const scale=Math.min(1.35,Math.max(.65,maxDim/Math.max(w,h)));const pix=page.toPixmap(mupdf.Matrix.scale(scale,scale),mupdf.ColorSpace.DeviceRGB,false,false);return{scale,promise:createImageBitmap(new Blob([pix.asPNG()],{type:'image/png'}))}}
function hardTarget(t){return key(t).length>=16||String(t).split(/[_\-\s./:]+/).filter(x=>x.length>=2).length>=4}
function anchorsFor(target,data){const anchors=String(target).split(/[_\-\s./:]+/).map(key).filter(x=>x.length>=3).sort((a,b)=>b.length-a.length).slice(0,4),ws=ordered(data),out=[];for(const a of anchors){let best=null;for(const w of ws){const s=sim(key(w.text),a);if(key(w.text)===a||s>=.84){if(!best||s>best.s)best={w,s}}}if(best)out.push(best)}return out}
function crop(bitmap,b,padX,padY){const x=Math.max(0,Math.floor(b.x0-padX)),y=Math.max(0,Math.floor(b.y0-padY)),x2=Math.min(bitmap.width,Math.ceil(b.x1+padX)),y2=Math.min(bitmap.height,Math.ceil(b.y1+padY)),c=document.createElement('canvas');c.width=Math.max(1,x2-x);c.height=Math.max(1,y2-y);c.getContext('2d').drawImage(bitmap,x,y,c.width,c.height,0,0,c.width,c.height);return{c,x,y}}
async function pageOCR(page,targets){const difficult=targets.filter(hardTarget),fast=render(page,1500),bitmap=await fast.promise;try{let data=await recognize(bitmap,'11'),hits=matchAll(data,targets,fast.scale);if([...hits.values()].some(x=>x.length))return hits;if(!difficult.length)return hits;
  const hi=render(page,2200),bm2=await hi.promise;try{data=await recognize(bm2,'11');hits=matchAll(data,targets,hi.scale);if(difficult.some(t=>(hits.get(t)||[]).length))return hits;
    for(const target of difficult){for(const a of anchorsFor(target,data)){const q=a.w.bbox,padX=Math.max(180,(q.x1-q.x0)*8),padY=Math.max(70,(q.y1-q.y0)*5),z=crop(bm2,q,padX,padY);const ad=await recognize(z.c,'6');const one=findOne(ad,target,hi.scale,z.x,z.y);if(one.length){hits.set(target,one);break}}}return hits
  }finally{bm2.close?.()}
}finally{bitmap.close?.()}}
export async function runRecognition(){const batch=window.__batchAnalysis;if(!Array.isArray(batch)||!batch.length)return{total:0};const status=document.querySelector('#batchStatus'),summary=document.querySelector('#batchSummary');let total=0;for(let ai=0;ai<batch.length;ai++){const a=batch[ai];if(!a||a.error||!a.data||a.kinds?.vector!==true)continue;const pending=(a.counts||[]).filter(c=>c.find?.trim()&&c.count===0&&c.annotationCount===0);if(!pending.length)continue;const doc=mupdf.PDFDocument.openDocument(a.data,'application/pdf');try{const pages=Array.isArray(a.vectorPages)&&a.vectorPages.length?a.vectorPages.map(x=>x-1):Array.from({length:doc.countPages()},(_,i)=>i);for(let pi=0;pi<pages.length;pi++){if(status)status.textContent=`OCR rápido · ${ai+1}/${batch.length} · página ${pi+1}/${pages.length} · ${a.name}`;const page=doc.loadPage(pages[pi]);const matches=await pageOCR(page,pending.map(c=>c.find));for(const c of pending){const m=matches.get(c.find)||[];if(!m.length)continue;c.ocrCount=(c.ocrCount||0)+m.length;c.ocrMatches=(c.ocrMatches||[]).concat(m.map(x=>({...x,page:pages[pi]+1})));c.pages=c.pages||[];if(!c.pages.includes(pages[pi]+1))c.pages.push(pages[pi]+1);total+=m.length}}}finally{doc.destroy()}}if(summary){summary.textContent=summary.textContent.replace(/ · \d+ coincidencias? vectorial(?:es)?\/OCR · ningún archivo modificado/,'')+` · ${total} coincidencia${total===1?'':'s'} vectorial/OCR · ningún archivo modificado`;summary.classList.remove('hidden')}if(status)status.textContent=total?`Reconocimiento terminado: ${total} coincidencia${total===1?'':'s'} vectorial/OCR detectada${total===1?'':'s'}. No se ha modificado ningún PDF.`:'Sin coincidencias vectoriales/OCR.';return{total}}
