import * as mupdf from 'https://cdn.jsdelivr.net/npm/mupdf@1.28.0/dist/mupdf.js';
let workerPromise;
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[‐‑‒–—−]/g,'-').replace(/\s+/g,' ').trim().toLowerCase();
const canonical=s=>norm(s).replace(/\s*[-]\s*/g,'-').replace(/\s*([:/_.])\s*/g,'$1');
const key=s=>canonical(s).replace(/[^a-z0-9]/g,'').replace(/o/g,'0');
function iou(a,b){const x=Math.max(0,Math.min(a[2],b[2])-Math.max(a[0],b[0])),y=Math.max(0,Math.min(a[3],b[3])-Math.max(a[1],b[1]));const inter=x*y,aa=Math.max(1,(a[2]-a[0])*(a[3]-a[1])),bb=Math.max(1,(b[2]-b[0])*(b[3]-b[1]));return inter/(aa+bb-inter)}
function lev(a,b){const p=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let q=[i];for(let j=1;j<=b.length;j++)q[j]=Math.min(q[j-1]+1,p[j]+1,p[j-1]+(a[i-1]===b[j-1]?0:1));for(let j=0;j<q.length;j++)p[j]=q[j]}return p[b.length]}
function sim(a,b){return a&&b?1-lev(a,b)/Math.max(a.length,b.length):0}
async function getWorker(){if(workerPromise)return workerPromise;workerPromise=import('https://esm.sh/tesseract.js@5.1.0').then(({createWorker})=>createWorker('spa+eng')).then(async w=>{try{await w.setParameters({tessedit_pageseg_mode:'11'})}catch(_){}return w}).catch(e=>{workerPromise=null;throw e});return workerPromise}
function matchData(data,target,scale,ox=0,oy=0){const wanted=canonical(target),wantedKey=key(target),found=[];const lines=(data?.lines||[]).filter(x=>x?.text?.trim()&&x.bbox);for(const l of lines){const k=key(l.text);const c=canonical(l.text);if(c===wanted||k===wantedKey||(k.length>=wantedKey.length*.85&&sim(k,wantedKey)>=.9)){found.push({bbox:[(l.bbox.x0+ox)/scale,(l.bbox.y0+oy)/scale,(l.bbox.x1+ox)/scale,(l.bbox.y1+oy)/scale],confidence:Number(l.confidence||0),similarity:sim(k,wantedKey),ocrText:l.text,exact:c===wanted||k===wantedKey});}}
if(found.length)return found;
const words=(data?.words||[]).filter(w=>w?.text?.trim()&&w.bbox);for(let i=0;i<words.length;i++){let text='',box=null,confidence=100;for(let j=i;j<Math.min(words.length,i+20);j++){const w=words[j],t=norm(w.text);text=text?text+' '+t:t;box=box?[Math.min(box[0],w.bbox.x0),Math.min(box[1],w.bbox.y0),Math.max(box[2],w.bbox.x1),Math.max(box[3],w.bbox.y1)]:[w.bbox.x0,w.bbox.y0,w.bbox.x1,w.bbox.y1];confidence=Math.min(confidence,Number(w.confidence||0));const c=canonical(text),k=key(text),exact=c===wanted||k===wantedKey,fuzzy=!exact&&confidence>=65&&sim(k,wantedKey)>=.88;if(exact||fuzzy){found.push({bbox:[(box[0]+ox)/scale,(box[1]+oy)/scale,(box[2]+ox)/scale,(box[3]+oy)/scale],confidence,similarity:sim(k,wantedKey),ocrText:text,exact});break}if(k.length>wantedKey.length+30)break}}
const unique=[];for(const m of found){const same=unique.find(u=>iou(u.bbox,m.bbox)>=.6);if(same){if(m.confidence>same.confidence)Object.assign(same,m)}else unique.push(m)}return unique}
async function recognizeCanvas(canvas,targets,scale,ox=0,oy=0,w){const r=await w.recognize(canvas);const out=new Map();for(const t of targets){const m=matchData(r?.data,t,scale,ox,oy);if(m.length)out.set(t,m)}return out}
async function pageOCR(page,targets){const scale=2,pix=page.toPixmap(mupdf.Matrix.scale(scale,scale),mupdf.ColorSpace.DeviceRGB,false,false),bitmap=await createImageBitmap(new Blob([pix.asPNG()],{type:'image/png'})),w=await getWorker(),pending=new Set(targets),found=new Map();const canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;canvas.getContext('2d').drawImage(bitmap,0,0);try{const fast=await recognizeCanvas(canvas,[...pending],scale,0,0,w);for(const [t,m] of fast){found.set(t,m);pending.delete(t)}}catch(_){}
if(pending.size){const complex=[...pending].filter(t=>key(t).length>=10||/[_.]/.test(t));if(complex.length){const cols=2,rows=2,tw=Math.ceil(bitmap.width/cols),th=Math.ceil(bitmap.height/rows);for(let ry=0;ry<rows&&pending.size;ry++)for(let cx=0;cx<cols&&pending.size;cx++){const x=Math.max(0,Math.floor(cx*tw-tw*.12)),y=Math.max(0,Math.floor(ry*th-th*.12)),x2=Math.min(bitmap.width,Math.ceil((cx+1)*tw+tw*.12)),y2=Math.min(bitmap.height,Math.ceil((ry+1)*th+th*.12)),c=document.createElement('canvas');c.width=x2-x;c.height=y2-y;c.getContext('2d').drawImage(bitmap,x,y,c.width,c.height,0,0,c.width,c.height);try{const part=await recognizeCanvas(c,[...pending],scale,x,y,w);for(const [t,m] of part){found.set(t,m);pending.delete(t)}}catch(_){}await new Promise(r=>setTimeout(r,0))}}}}
bitmap.close?.();return found}
export async function runRecognition(){const batch=window.__batchAnalysis;if(!Array.isArray(batch)||!batch.length)return {total:0};const status=document.querySelector('#batchStatus'),summary=document.querySelector('#batchSummary');let total=0;for(let ai=0;ai<batch.length;ai++){const a=batch[ai];if(!a||a.error||!a.data)continue;const doc=mupdf.PDFDocument.openDocument(a.data,'application/pdf');try{for(let pi=0;pi<doc.countPages();pi++){if(status)status.textContent=`Reconociendo vector/OCR · ${ai+1}/${batch.length} · página ${pi+1} · ${a.name}`;if(a.kinds?.vector!==true)continue;const page=doc.loadPage(pi),candidates=(a.counts||[]).filter(c=>c.find?.trim()&&c.count===0&&c.annotationCount===0);if(!candidates.length)continue;const found=await pageOCR(page,candidates.map(c=>c.find));for(const c of candidates){const matches=found.get(c.find)||[];if(!matches.length)continue;c.ocrCount=(c.ocrCount||0)+matches.length;c.ocrMatches=(c.ocrMatches||[]).concat(matches.map(m=>({...m,page:pi+1})));c.pages=c.pages||[];if(!c.pages.includes(pi+1))c.pages.push(pi+1);total+=matches.length}}}finally{doc.destroy()}}const rows=[...document.querySelectorAll('.batch-result')];batch.forEach((a,i)=>{const row=rows[i],span=row?.querySelector(':scope > span');if(!span)return;const hits=(a.counts||[]).filter(c=>c.ocrCount).map(c=>`${c.ocrCount}× ${c.find} (vector/OCR)`);if(hits.length&&!span.textContent.includes('vector/OCR'))span.append(document.createTextNode(' · '+hits.join(' · ')))});if(summary){summary.textContent=summary.textContent.replace(/ · \d+ coincidencias? vectorial(?:es)?\/OCR · ningún archivo modificado/,'')+` · ${total} coincidencia${total===1?'':'s'} vectorial${total===1?'':'es'}/OCR · ningún archivo modificado`;summary.classList.remove('hidden')}if(status)status.textContent=total?`Reconocimiento terminado: ${total} coincidencia${total===1?'':'s'} vectorial${total===1?'':'s'} detectada${total===1?'':'s'}. No se ha modificado ningún PDF.`:'Sin coincidencias vectoriales/OCR.';return {total}}
