import * as mupdf from 'https://cdn.jsdelivr.net/npm/mupdf@1.28.0/dist/mupdf.js';
const pool=[];let poolReady=null;
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[‐‑‒–—−]/g,'-').replace(/\s+/g,' ').trim().toLowerCase();
const key=s=>norm(s).replace(/[^a-z0-9]/g,'').replace(/o/g,'0').replace(/[il]/g,'1').replace(/z/g,'2').replace(/s/g,'5');
function lev(a,b){const p=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){const q=[i];for(let j=1;j<=b.length;j++)q[j]=Math.min(q[j-1]+1,p[j]+1,p[j-1]+(a[i-1]===b[j-1]?0:1));for(let j=0;j<q.length;j++)p[j]=q[j]}return p[b.length]}
const sim=(a,b)=>a&&b?1-lev(a,b)/Math.max(a.length,b.length):0;
const iou=(a,b)=>{const x=Math.max(0,Math.min(a[2],b[2])-Math.max(a[0],b[0])),y=Math.max(0,Math.min(a[3],b[3])-Math.max(a[1],b[1])),z=x*y;return z/(Math.max(1,(a[2]-a[0])*(a[3]-a[1]))+Math.max(1,(b[2]-b[0])*(b[3]-b[1]))-z)};
async function initPool(){if(poolReady)return poolReady;poolReady=(async()=>{const {createWorker}=await import('https://esm.sh/tesseract.js@5.1.0');for(let i=0;i<3;i++)pool.push(await createWorker('spa+eng'));return pool})().catch(e=>{poolReady=null;throw e});return poolReady}
let nextWorker=0;
async function ocr(canvas,mode){const ws=await initPool(),w=ws[nextWorker++%ws.length];await w.setParameters({preserve_interword_spaces:'1',user_defined_dpi:'220',tessedit_pageseg_mode:String(mode)});return (await w.recognize(canvas))?.data||null}
function ordered(ws){return (ws||[]).filter(w=>w?.text?.trim()&&w.bbox).sort((a,b)=>{const ay=(a.bbox.y0+a.bbox.y1)/2,by=(b.bbox.y0+b.bbox.y1)/2,h=Math.max(8,((a.bbox.y1-a.bbox.y0)+(b.bbox.y1-b.bbox.y0))/2);return Math.abs(ay-by)<h*.8?a.bbox.x0-b.bbox.x0:ay-by})}
function union(ws){let b=null;for(const w of ws){const q=w.bbox;b=b?[Math.min(b[0],q.x0),Math.min(b[1],q.y0),Math.max(b[2],q.x1),Math.max(b[3],q.y1)]:[q.x0,q.y0,q.x1,q.y1]}return b}
function find(data,target,scale,ox=0,oy=0){const want=key(target),out=[],ws=ordered(data?.words);for(let i=0;i<ws.length;i++){let s='',pick=[];for(let j=i;j<Math.min(ws.length,i+35);j++){pick.push(ws[j]);s+=ws[j].text;const k=key(s),ratio=Math.min(k.length,want.length)/Math.max(k.length,want.length),score=sim(k,want),exact=k===want;if(exact||(ratio>=.8&&score>=.88)){const b=union(pick),conf=Math.min(...pick.map(w=>Number(w.confidence)||50));if(b&&(exact||conf>=40))out.push({bbox:[(b[0]+ox)/scale,(b[1]+oy)/scale,(b[2]+ox)/scale,(b[3]+oy)/scale],confidence:conf,similarity:score,ocrText:s,exact});break}if(k.length>want.length+45)break}}const u=[];for(const m of out){const same=u.find(x=>iou(x.bbox,m.bbox)>.55);if(!same)u.push(m);else if(m.exact||m.confidence>same.confidence)Object.assign(same,m)}return u}
function anchorCandidates(data,target){const anchors=String(target).split(/[_\-\s./:]+/).filter(x=>x.length>=2).map(key),ws=ordered(data?.words),out=[];for(const a of anchors){let best=null;for(const w of ws){const score=sim(key(w.text),a);if(key(w.text)===a||score>=.86){if(!best||score>best.score)best={w,score}}}if(best)out.push(best)}return out.sort((a,b)=>b.score-a.score).slice(0,3)}
function crop(bitmap,b){const px=Math.max(160,(b.x1-b.x0)*10),py=Math.max(80,(b.y1-b.y0)*5),x=Math.max(0,Math.floor(b.x0-px)),y=Math.max(0,Math.floor(b.y0-py)),x2=Math.min(bitmap.width,Math.ceil(b.x1+px)),y2=Math.min(bitmap.height,Math.ceil(b.y1+py)),c=document.createElement('canvas');c.width=x2-x;c.height=y2-y;c.getContext('2d').drawImage(bitmap,x,y,c.width,c.height,0,0,c.width,c.height);return{c,x,y}}
async function pageOCR(page,target){const complex=key(target).length>=18||String(target).split(/[_\-\s./:]+/).length>=4;const scale=complex?1.8:1.5,pix=page.toPixmap(mupdf.Matrix.scale(scale,scale),mupdf.ColorSpace.DeviceRGB,false,false),bitmap=await createImageBitmap(new Blob([pix.asPNG()],{type:'image/png'}));try{const d=await ocr(bitmap,11);let hits=find(d,target,scale);if(hits.length)return hits;if(complex){for(const a of anchorCandidates(d,target)){const q=crop(bitmap,a.w),ad=await ocr(q.c,6);hits=find(ad,target,scale,q.x,q.y);if(hits.length)return hits}const hi=2.4,p2=page.toPixmap(mupdf.Matrix.scale(hi,hi),mupdf.ColorSpace.DeviceRGB,false,false),bm2=await createImageBitmap(new Blob([p2.asPNG()],{type:'image/png'}));try{hits=find(await ocr(bm2,6),target,hi);if(hits.length)return hits}finally{bm2.close?.()}}return[]}finally{bitmap.close?.()}}
async function closePool(){for(const w of pool.splice(0))try{await w.terminate()}catch(_){}poolReady=null}
export async function runRecognition(){const batch=window.__batchAnalysis;if(!Array.isArray(batch)||!batch.length)return{total:0};const status=document.querySelector('#batchStatus'),summary=document.querySelector('#batchSummary');let total=0;try{for(let ai=0;ai<batch.length;ai++){const a=batch[ai];if(!a||a.error||!a.data)continue;const doc=mupdf.PDFDocument.openDocument(a.data,'application/pdf');try{const pages=Array.isArray(a.vectorPages)&&a.vectorPages.length?a.vectorPages.map(x=>x-1):Array.from({length:doc.countPages()},(_,i)=>i);for(let start=0;start<pages.length;start+=3){const jobs=pages.slice(start,start+3).map(async pi=>{if(status)status.textContent=`Reconociendo vector/OCR · ${ai+1}/${batch.length} · página ${pi+1}/${pages.length} · ${a.name}`;const page=doc.loadPage(pi);const out=[];for(const c of a.counts||[]){if(!c.find?.trim()||c.count>0||c.annotationCount>0)continue;const m=await pageOCR(page,c.find);if(m.length)out.push({c,m,pi})}return out});for(const group of await Promise.all(jobs))for(const {c,m,pi} of group){c.ocrCount=(c.ocrCount||0)+m.length;c.ocrMatches=(c.ocrMatches||[]).concat(m.map(x=>({...x,page:pi+1})));c.pages=c.pages||[];if(!c.pages.includes(pi+1))c.pages.push(pi+1);total+=m.length}}}finally{doc.destroy()}}}finally{await closePool()}if(summary){summary.textContent=summary.textContent.replace(/ · \d+ coincidencias? vectorial(?:es)?\/OCR · ningún archivo modificado/,'')+` · ${total} coincidencia${total===1?'':'s'} vectorial/OCR · ningún archivo modificado`;summary.classList.remove('hidden')}if(status)status.textContent=total?`Reconocimiento terminado: ${total} coincidencia${total===1?'':'s'} vectorial/OCR detectada${total===1?'':'s'}. No se ha modificado ningún PDF.`:'Sin coincidencias vectoriales/OCR.';return{total}}
