import * as mupdf from 'https://cdn.jsdelivr.net/npm/mupdf@1.28.0/dist/mupdf.js';
let workerPromise;
const diag=(stage,detail='',extra={})=>{try{const d={time:new Date().toISOString(),stage,detail,...extra};if(typeof window.__ocrDiagnostic==='function')window.__ocrDiagnostic(d);console.debug('[OCR]',stage,detail,extra)}catch(_){}};
const withDiag=async(stage,fn,extra={})=>{const t=performance.now();diag(stage,'INICIO',extra);try{const r=await fn();diag(stage,'OK', {...extra,ms:Math.round(performance.now()-t)});return r}catch(e){diag(stage,'ERROR: '+(e?.message||String(e)),{...extra,ms:Math.round(performance.now()-t)});throw e}};
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[‐‑‒–—−]/g,'-').replace(/\s+/g,' ').trim().toLowerCase();
const canonical=s=>norm(s).replace(/\s*[-]\s*/g,'-').replace(/\s*([:/_.])\s*/g,'$1');
const key=s=>canonical(s).replace(/[^a-z0-9]/g,'').replace(/o/g,'0');
function iou(a,b){const x=Math.max(0,Math.min(a[2],b[2])-Math.max(a[0],b[0])),y=Math.max(0,Math.min(a[3],b[3])-Math.max(a[1],b[1]));const inter=x*y,aa=Math.max(1,(a[2]-a[0])*(a[3]-a[1])),bb=Math.max(1,(b[2]-b[0])*(b[3]-b[1]));return inter/(aa+bb-inter)}
function lev(a,b){const p=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let q=[i];for(let j=1;j<=b.length;j++)q[j]=Math.min(q[j-1]+1,p[j]+1,p[j-1]+(a[i-1]===b[j-1]?0:1));for(let j=0;j<q.length;j++)p[j]=q[j]}return p[b.length]}
function sim(a,b){return a&&b?1-lev(a,b)/Math.max(a.length,b.length):0}
async function getWorker(){if(workerPromise)return workerPromise;return workerPromise=withDiag('worker','Cargando Tesseract').then(()=>import('https://esm.sh/tesseract.js@5.1.0')).then(({createWorker})=>createWorker('spa+eng')).then(async w=>{try{await w.setParameters({tessedit_pageseg_mode:'11'})}catch(_){}diag('worker','LISTO');return w}).catch(e=>{workerPromise=null;diag('worker','ERROR: '+(e?.message||String(e)));throw e});}
function findWords(data,target,scale,ox=0,oy=0){const wanted=canonical(target),wantedKey=key(target),words=(data?.words||[]).filter(w=>w?.text?.trim()&&w.bbox),found=[];for(let i=0;i<words.length;i++){let text='',box=null,confidence=100;for(let j=i;j<Math.min(words.length,i+20);j++){const w=words[j],t=norm(w.text);text=text?text+' '+t:t;box=box?[Math.min(box[0],w.bbox.x0),Math.min(box[1],w.bbox.y0),Math.max(box[2],w.bbox.x1),Math.max(box[3],w.bbox.y1)]:[w.bbox.x0,w.bbox.y0,w.bbox.x1,w.bbox.y1];confidence=Math.min(confidence,Number(w.confidence||0));const c=canonical(text),k=key(text),exact=c===wanted||k===wantedKey,fuzzy=!exact&&confidence>=70&&sim(k,wantedKey)>=.88;if(exact||fuzzy){found.push({bbox:[(box[0]+ox)/scale,(box[1]+oy)/scale,(box[2]+ox)/scale,(box[3]+oy)/scale],confidence,similarity:sim(k,wantedKey),ocrText:text,exact});break}if(k.length>wantedKey.length+30)break}}const unique=[];for(const m of found){const same=unique.find(u=>iou(u.bbox,m.bbox)>=.6);if(same){if(m.confidence>same.confidence)Object.assign(same,m)}else unique.push(m)}return unique}
async function recognizeCanvas(canvas,target,pageNo,mode){return withDiag('ocr.recognize',`Tesseract PSM ${mode}`,{target,page:pageNo,mode,px:`${canvas.width}x${canvas.height}`}).then(async()=>{const w=await getWorker();try{await w.setParameters({tessedit_pageseg_mode:String(mode),preserve_interword_spaces:'1'})}catch(_){}return (await w.recognize(canvas))?.data||null})}
async function fastPageOCR(page,target,pageNo){return withDiag('ocr.fast',`Pasada rápida 1.35×`,{target,page:pageNo},async()=>{const scale=1.35,pix=page.toPixmap(mupdf.Matrix.scale(scale,scale),mupdf.ColorSpace.DeviceRGB,false,false);const bitmap=await createImageBitmap(new Blob([pix.asPNG()],{type:'image/png'}));const canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;canvas.getContext('2d').drawImage(bitmap,0,0);try{const data=await recognizeCanvas(canvas,target,pageNo,'11');const found=findWords(data,target,scale);diag('ocr.fast.match',found.length?`ENCONTRADO (${found.length})`:'sin coincidencia',{target,page:pageNo,ocrText:found[0]?.ocrText||''});return found}finally{bitmap.close?.()}})}
async function quadrantPageOCR(page,target,pageNo){return withDiag('ocr.fallback',`Fallback 2× · 4 cuadrantes`,{target,page:pageNo},async()=>{const scale=2,pix=page.toPixmap(mupdf.Matrix.scale(scale,scale),mupdf.ColorSpace.DeviceRGB,false,false),bitmap=await createImageBitmap(new Blob([pix.asPNG()],{type:'image/png'})),w=await getWorker(),cols=2,rows=2,tw=Math.ceil(bitmap.width/cols),th=Math.ceil(bitmap.height/rows),all=[];try{let qi=0;for(let ry=0;ry<rows;ry++)for(let cx=0;cx<cols;cx++){qi++;const x=Math.max(0,Math.floor(cx*tw-tw*.12)),y=Math.max(0,Math.floor(ry*th-th*.12)),x2=Math.min(bitmap.width,Math.ceil((cx+1)*tw+tw*.12)),y2=Math.min(bitmap.height,Math.ceil((ry+1)*th+th*.12)),canvas=document.createElement('canvas');canvas.width=x2-x;canvas.height=y2-y;canvas.getContext('2d').drawImage(bitmap,x,y,canvas.width,canvas.height,0,0,canvas.width,canvas.height);diag('ocr.quadrant',`Cuadrante ${qi}/4`,{target,page:pageNo,quadrant:qi});try{all.push(...findWords(await recognizeCanvas(canvas,target,pageNo,'11'),target,scale,x,y))}catch(e){diag('ocr.quadrant','ERROR: '+(e?.message||String(e)),{target,page:pageNo,quadrant:qi})}await new Promise(r=>setTimeout(r,0))}}finally{bitmap.close?.()}const unique=[];for(const m of all){const same=unique.find(u=>iou(u.bbox,m.bbox)>=.6);if(same){if(m.confidence>same.confidence)Object.assign(same,m)}else unique.push(m)}diag('ocr.fallback.match',unique.length?`ENCONTRADO (${unique.length})`:'sin coincidencia',{target,page:pageNo});return unique})}
async function pageOCR(page,target,pageNo){diag('ocr.page','INICIO',{target,page:pageNo});try{const fast=await fastPageOCR(page,target,pageNo);if(fast.length){diag('ocr.page','FIN · encontrado en pasada rápida',{target,page:pageNo});return fast}diag('ocr.page','Pasada rápida sin coincidencia; activando fallback',{target,page:pageNo});const q=await quadrantPageOCR(page,target,pageNo);diag('ocr.page',q.length?'FIN · encontrado en fallback':'FIN · sin coincidencia',{target,page:pageNo});return q}catch(e){diag('ocr.page','ERROR: '+(e?.message||String(e)),{target,page:pageNo});throw e}}
export async function runRecognition(){const batch=window.__batchAnalysis;if(!Array.isArray(batch)||!batch.length)return{total:0};const status=document.querySelector('#batchStatus'),summary=document.querySelector('#batchSummary');let total=0;diag('recognition','INICIO',{files:batch.length});for(let ai=0;ai<batch.length;ai++){const a=batch[ai];if(!a||a.error||!a.data){diag('file','OMITIDO · error/datos',{file:a?.name||''});continue}const doc=mupdf.PDFDocument.openDocument(a.data,'application/pdf');try{for(let pi=0;pi<doc.countPages();pi++){if(status)status.textContent=`Reconociendo vector/OCR · ${ai+1}/${batch.length} · página ${pi+1} · ${a.name}`;if(a.kinds?.vector!==true){diag('page','OMITIDA · no clasificada vectorial',{file:a.name,page:pi+1});continue}const page=doc.loadPage(pi);diag('page','PROCESANDO',{file:a.name,page:pi+1});for(const c of a.counts||[]){if(!c.find?.trim()||c.count>0||c.annotationCount>0)continue;try{const matches=await pageOCR(page,c.find,pi+1);if(!matches.length)continue;c.ocrCount=(c.ocrCount||0)+matches.length;c.ocrMatches=(c.ocrMatches||[]).concat(matches.map(m=>({...m,page:pi+1})));c.pages=c.pages||[];if(!c.pages.includes(pi+1))c.pages.push(pi+1);total+=matches.length}catch(e){diag('rule','ERROR',{file:a.name,page:pi+1,target:c.find,error:e?.message||String(e)})}}}}finally{doc.destroy()}}diag('recognition','FIN',{total});const rows=[...document.querySelectorAll('.batch-result')];batch.forEach((a,i)=>{const row=rows[i],span=row?.querySelector(':scope > span');if(!span)return;const hits=(a.counts||[]).filter(c=>c.ocrCount).map(c=>`${c.ocrCount}× ${c.find} (vector/OCR)`);if(hits.length&&!span.textContent.includes('vector/OCR'))span.append(document.createTextNode(' · '+hits.join(' · ')))});if(summary){summary.textContent=summary.textContent.replace(/ · \d+ coincidencias? vectorial(?:es)?\/OCR · ningún archivo modificado/,'')+` · ${total} coincidencia${total===1?'':'s'} vectorial/OCR · ningún archivo modificado`;summary.classList.remove('hidden')}if(status)status.textContent=total?`Reconocimiento terminado: ${total} coincidencia${total===1?'':'s'} vectorial/OCR detectada${total===1?'':'s'}. No se ha modificado ningún PDF.`:'Sin coincidencias vectoriales/OCR.';return{total}}
