import * as mupdf from 'https://cdn.jsdelivr.net/npm/mupdf@1.28.0/dist/mupdf.js';
let workerPromise=null;
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[‐‑‒–—−]/g,'-').replace(/\s+/g,' ').trim().toLowerCase();
const key=s=>norm(s).replace(/[^a-z0-9]/g,'').replace(/o/g,'0').replace(/[il]/g,'1');
const lev=(a,b)=>{if(a===b)return 0;if(!a)return b.length;if(!b)return a.length;let p=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){const q=[i];for(let j=1;j<=b.length;j++)q[j]=Math.min(q[j-1]+1,p[j]+1,p[j-1]+(a[i-1]===b[j-1]?0:1));p=q}return p[b.length]};
const sim=(a,b)=>a&&b?1-lev(a,b)/Math.max(a.length,b.length):0;
const iou=(a,b)=>{const x=Math.max(0,Math.min(a[2],b[2])-Math.max(a[0],b[0])),y=Math.max(0,Math.min(a[3],b[3])-Math.max(a[1],b[1])),z=x*y;return z/(Math.max(1,(a[2]-a[0])*(a[3]-a[1]))+Math.max(1,(b[2]-b[0])*(b[3]-b[1]))-z)};
async function worker(){if(workerPromise)return workerPromise;workerPromise=import('https://esm.sh/tesseract.js@5.1.0').then(({createWorker})=>createWorker('eng')).then(async w=>{await w.setParameters({preserve_interword_spaces:'1',user_defined_dpi:'150',tessedit_pageseg_mode:'11'});return w}).catch(e=>{workerPromise=null;throw e});return workerPromise}
function ordered(data){return (data?.words||[]).filter(w=>w?.text?.trim()&&w.bbox).sort((a,b)=>{const ay=(a.bbox.y0+a.bbox.y1)/2,by=(b.bbox.y0+b.bbox.y1)/2,h=Math.max(8,((a.bbox.y1-a.bbox.y0)+(b.bbox.y1-b.bbox.y0))/2);return Math.abs(ay-by)<h*.8?a.bbox.x0-b.bbox.x0:ay-by})}
function union(ws){let b=null;for(const w of ws){const q=w.bbox;b=b?[Math.min(b[0],q.x0),Math.min(b[1],q.y0),Math.max(b[2],q.x1),Math.max(b[3],q.y1)]:[q.x0,q.y0,q.x1,q.y1]}return b}
function matchWords(data,targets,scale,ox=0,oy=0){const ws=ordered(data),out=new Map(targets.map(t=>[t,[]]));for(const target of targets){const want=key(target);if(!want)continue;for(let i=0;i<ws.length;i++){let s='',pick=[];for(let j=i;j<Math.min(ws.length,i+28);j++){pick.push(ws[j]);s+=ws[j].text;const k=key(s);const exact=k===want;const ratio=Math.min(k.length,want.length)/Math.max(k.length,want.length);if(exact||(ratio>=.8&&sim(k,want)>=.84)){const b=union(pick),conf=Math.min(...pick.map(w=>Number(w.confidence)||50));if(b&&(exact||conf>=40)){out.get(target).push({bbox:[(b[0]+ox)/scale,(b[1]+oy)/scale,(b[2]+ox)/scale,(b[3]+oy)/scale],confidence:conf,similarity:sim(k,want),ocrText:s,exact})}break}if(k.length>want.length+35)break}}}for(const [t,arr] of out){const u=[];for(const m of arr){const same=u.find(x=>iou(x.bbox,m.bbox)>.55);if(!same)u.push(m);else if(m.exact||m.confidence>same.confidence)Object.assign(same,m)}out.set(t,u)}return out}
function render(page,maxDim=3000){const b=page.getBounds?.()||[0,0,1000,1000];const w=Math.max(1,b[2]-b[0]),h=Math.max(1,b[3]-b[1]);const scale=Math.min(2,Math.max(.7,maxDim/Math.max(w,h)));const pix=page.toPixmap(mupdf.Matrix.scale(scale,scale),mupdf.ColorSpace.DeviceRGB,false,false);return {scale,promise:createImageBitmap(new Blob([pix.asPNG()],{type:'image/png'}))}}
async function ocrBitmap(bitmap,mode='11'){const w=await worker();await w.setParameters({tessedit_pageseg_mode:String(mode)});return (await w.recognize(bitmap))?.data||null}
function crop(bitmap,b,pad=140){const x=Math.max(0,Math.floor(b.x0-pad)),y=Math.max(0,Math.floor(b.y0-pad*.55)),x2=Math.min(bitmap.width,Math.ceil(b.x1+pad)),y2=Math.min(bitmap.height,Math.ceil(b.y1+pad*.55));const c=document.createElement('canvas');c.width=Math.max(1,x2-x);c.height=Math.max(1,y2-y);c.getContext('2d').drawImage(bitmap,x,y,c.width,c.height,0,0,c.width,c.height);return{c,x,y}}
function anchors(data,target){const as=String(target).split(/[_\-\s./:]+/).map(x=>key(x)).filter(x=>x.length>=3).sort((a,b)=>b.length-a.length).slice(0,4),ws=ordered(data),out=[];for(const a of as){let best=null;for(const w of ws){const k=key(w.text);const s=sim(k,a);if(k===a||s>=.84){if(!best||s>best.score)best={w,score:s}}}if(best)out.push(best)}return out}
async function pageOCR(page,targets){const {scale,promise}=render(page,3000),bitmap=await promise;try{let data=await ocrBitmap(bitmap,'11');let hits=matchWords(data,targets,scale);if([...hits.values()].some(x=>x.length))return hits;const hard=targets.filter(t=>key(t).length>=16||String(t).split(/[_\-\s./:]+/).filter(x=>x.length>=2).length>=4);if(!hard.length)return hits;for(const target of hard){for(const a of anchors(data,target)){const q=crop(bitmap,a.w,220);const ad=await ocrBitmap(q.c,'6');const one=matchWords(ad,[target],scale,q.x,q.y).get(target)||[];if(one.length){hits.set(target,one);break}}}return hits}finally{bitmap.close?.()}}
export async function runRecognition(){const batch=window.__batchAnalysis;if(!Array.isArray(batch)||!batch.length)return{total:0};const status=document.querySelector('#batchStatus'),summary=document.querySelector('#batchSummary');let total=0;try{for(let ai=0;ai<batch.length;ai++){const a=batch[ai];if(!a||a.error||!a.data||a.kinds?.vector!==true)continue;const pending=(a.counts||[]).filter(c=>c.find?.trim()&&c.count===0&&c.annotationCount===0);if(!pending.length)continue;const doc=mupdf.PDFDocument.openDocument(a.data);try{const pages=Array.isArray(a.vectorPages)&&a.vectorPages.length?a.vectorPages.map(x=>x-1):[];for(let pi=0;pi<pages.length;pi++){if(status)status.textContent=`OCR rápido · ${ai+1}/${batch.length} · página ${pi+1}/${pages.length} · ${a.name}`;const page=doc.loadPage(pages[pi]);const targets=pending.map(c=>c.find);const matches=await pageOCR(page,targets);for(const c of pending){const m=matches.get(c.find)||[];if(!m.length)continue;c.ocrCount=(c.ocrCount||0)+m.length;c.ocrMatches=(c.ocrMatches||[]).concat(m.map(x=>({...x,page:pages[pi]+1})));c.pages=c.pages||[];if(!c.pages.includes(pages[pi]+1))c.pages.push(pages[pi]+1);total+=m.length}}}finally{doc.destroy()}}}finally{if(summary){summary.textContent=summary.textContent.replace(/ · \d+ coincidencias? vectorial(?:es)?\/OCR · ningún archivo modificado/,'')+` · ${total} coincidencia${total===1?'':'s'} vectorial/OCR · ningún archivo modificado`;summary.classList.remove('hidden')}if(status)status.textContent=total?`Reconocimiento terminado: ${total} coincidencia${total===1?'':'s'} vectorial/OCR detectada${total===1?'':'s'}. No se ha modificado ningún PDF.`:'Sin coincidencias vectoriales/OCR.'}return{total}}
