from pathlib import Path
p=Path('foxit-index-engine.mjs')
s=p.read_text()
old="export async function deleteExact(bytes,selectedOrdinals){let base=null,page=null,work=null,wp=null,check=null,cp=null;try{base=mupdf.PDFDocument.openDocument(bytes,'application/pdf');page=base.loadPage(0);const visual=collectVisual(page),idx=buildCompactIndex(page);if(idx.incomplete)throw new Error('índice incompleto');const map=mapSelected(visual,idx,selectedOrdinals);if(map.ids.length!==selectedOrdinals.length)throw new Error('mapeo no único: '+map.mode);const plan=await makePlan(idx,map.ids);work=mupdf.PDFDocument.openDocument(bytes,'application/pdf');await applyPlan(work,plan);wp=work.loadPage(0);const after=collectVisual(wp);if(!verifyOrderedMinus(visual,after,selectedOrdinals))throw new Error('original - azul no coincide');const mode=work.canBeSavedIncrementally?.()===false?'':'incremental',buf=work.saveToBuffer(mode),out=new Uint8Array(U(buf));check=mupdf.PDFDocument.openDocument(out,'application/pdf');cp=check.loadPage(0);const saved=collectVisual(cp);if(!verifyOrderedMinus(visual,saved,selectedOrdinals))throw new Error('guardado no conserva original - azul');return{out,mapMode:map.mode,streams:plan.length,before:visual.length,after:saved.length}}finally{try{cp?.destroy?.()}catch(_){}try{check?.destroy?.()}catch(_){}try{wp?.destroy?.()}catch(_){}try{work?.destroy?.()}catch(_){}try{page?.destroy?.()}catch(_){}try{base?.destroy?.()}catch(_){}}}"
new="export async function deleteExactIndexed(bytes,visual,idx,selectedOrdinals){let work=null,wp=null,check=null,cp=null;try{if(idx.incomplete)throw new Error('índice incompleto');const map=mapSelected(visual,idx,selectedOrdinals);if(map.ids.length!==selectedOrdinals.length)throw new Error('mapeo no único: '+map.mode);const plan=await makePlan(idx,map.ids);work=mupdf.PDFDocument.openDocument(bytes,'application/pdf');await applyPlan(work,plan);wp=work.loadPage(0);const after=collectVisual(wp);if(!verifyOrderedMinus(visual,after,selectedOrdinals))throw new Error('original - azul no coincide');const mode=work.canBeSavedIncrementally?.()===false?'':'incremental',buf=work.saveToBuffer(mode),out=new Uint8Array(U(buf));check=mupdf.PDFDocument.openDocument(out,'application/pdf');cp=check.loadPage(0);const saved=collectVisual(cp);if(!verifyOrderedMinus(visual,saved,selectedOrdinals))throw new Error('guardado no conserva original - azul');return{out,mapMode:map.mode,streams:plan.length,before:visual.length,after:saved.length}}finally{try{cp?.destroy?.()}catch(_){}try{check?.destroy?.()}catch(_){}try{wp?.destroy?.()}catch(_){}try{work?.destroy?.()}catch(_){}}}\nexport async function deleteExact(bytes,selectedOrdinals){let base=null,page=null;try{base=mupdf.PDFDocument.openDocument(bytes,'application/pdf');page=base.loadPage(0);const visual=collectVisual(page),idx=buildCompactIndex(page);return await deleteExactIndexed(bytes,visual,idx,selectedOrdinals)}finally{try{page?.destroy?.()}catch(_){}try{base?.destroy?.()}catch(_){}}}"
if old not in s:
    raise SystemExit('deleteExact target not found')
s=s.replace(old,new,1)
p.write_text(s)
print('patched delete path to reuse cached visual/index')
