import * as mupdf from 'https://cdn.jsdelivr.net/npm/mupdf@1.28.0/dist/mupdf.js';
let workerPromise=null;
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[‐‑‒–—−]/g,'-').replace(/\s+/g,' ').trim().toLowerCase();
const key=s=>norm(s).replace(/[^a-z0-9]/g,'').replace(/o/g,'0').replace(/[il]/g,'1');
const lev=(a,b)=>{const p=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){const q=[i];for(let j=1;j<=b.length;j++)q[j]=Math.min(q[j-1]+1,p[j]+1,p[j-1]+(a[i-1]===b[j-1]?0:1));for(let j=0;j<q.length;j++)p[j]=q[j]}return p[b.length]};
const sim=(a,b)=>a&&b?1-lev(a,b)/Math.max(a.length,b.length):0;
const iou=(a,b)=>{const x=Math.max(0,Math.min(a[2],b[2])-Math.max(a[0],b[0])),y=Math.max(0,Math.min(a[3],b[3])-Math.max(a[1],b[1])),z=x*y;return z/(Math.max(1,(a[2]-a[0])*(a[3]-a[1]))+Math.max(1,(b[2]-b[0])*(b[3]-b[1]))-z)};
async function worker(){if(workerPromise)return workerPromise;const lang=/[áéíóúüñ]/i.test(window.__ocrTarget||'')?'spa+eng':'eng';workerPromise=import('https://esm.sh/tesseract.js@5.1.0').then(({createWorker})=>createWorker(lang)).then(async w=>{await w.setParameters({tessedit_pageseg_mode:'11',preserve_interword_spaces:'1',user_defined_dpi:'180'});return w}).catch(e=>{workerPromise=null;throw e});return workerPromise}
function words(data,target,scale,ox=0,oy=0){const want=key(target),ws=(data?.words||[]).filter(w=>w?.text?.trim()&&w.bbox),out=[];for(let i=0;i<ws.length;i++){let s='',pick=[];for(let j=i;j<Math.min(ws.length,i+28);j++){pick.push(ws[j]);s+=ws[j].text;const k=key(s),ratio=Math.min(k.length,want.length)/Math.max(k.length,want.length);if(k===want||(ratio>=.8&&sim(k,want)>=.84)){const b=pick.reduce((r,w)=>[Math.min(r[0],w.bbox.x0),Math.min(r[1],w.bbox.y0),Math.max(r[2],w.bbox.x1),Math.max(r[3],w.bbox.y1)],[Infinity,Infinity,-Infinity,-Infinity]);out.push({bbox:[(b[0]+ox)/scale,(b[1]+oy)/scale,(b[2]+ox)/scale,(b[3]+oy)/scale],confidence:Math.min(...pick.map(w=>Number(w.confidence)||50)),similarity:sim(k,want),ocrText:s});break}if(k.length>want.length+35)break}}return out}
async function recognize(canvas,target,scale,ox=0,oy=0){window.__ocrTarget=target;const w=await worker();const r=await w.recognize(canvas);return words(r?.data,target,scale,ox,oy)}
function render(page,scale){const pix=page.toPixmap(mupdf.Matrix.scale(scale,scale),mupdf.ColorSpace.DeviceRGB,false,false);return createImageBitmap(new Blob([pix.asPNG()],{type:'image/png'}))}
async function pageOCR(page,target){const complex=key(target).length>=18||String(target).split(/[_\-\s./:]+/).length>=4;const scale=complex?1.5:1.25;const bm=await render(page,scale);try{let hits=await recognize(bm,target,scale);if(hits.length)return hits;if(!complex)return[];const cols=2,rows=2,tw=Math.ceil(bm.width/cols),th=Math.ceil(bm.height/rows);for(let ry=0;ry<rows;ry++)for(let cx=0;cx<cols;cx++){const x=Math.max(0,Math.floor(cx*tw-tw*.1)),y=Math.max(0,Math.floor(ry*th-th*.1)),x2=Math.min(bm.width,Math.ceil((cx+1)*tw+tw*.1)),y2=Math.min(bm.height,Math.ceil((ry+1)*th+th*.1)),c=document.createElement('canvas');c.width=x2-x;c.height=y2-y;c.getContext('2d').drawImage(bm,x,y,c.width,c.height,0,0,c.width,c.height);hits=await recognize(c,target,scale,x,y);if(hits.length)return hits}return[]}finally{bm.close?.()}}
export async function runRecognition(){const batch=window.__batchAnalysis;if(!Array.isArray(batch)||!batch.length)return{total:0};const status=document.querySelector('#batchStatus'),summary=document.querySelector('#batchSummary');let total=0;for(let ai=0;ai<batch.length;ai++){const a=batch[ai];if(!a||a.error||!a.data||a.kinds?.vector!==true)continue;const doc=mupdf.PDFDocument.openDocument(a.data,'application/pdf');try{for(let pi=0;pi<doc.countPages();pi++){const pending=(a.counts||[]).filter(c=>c.find?.trim()&&c.count===0&&c.annotationCount===0);if(!pending.length)break;if(status)status.textContent=`Reconociendo vector/OCR · ${ai+1}/${batch.length} · página ${pi+1}/${doc.countPages()} · ${a.name}`;const page=doc.loadPage(pi);for(const c of pending){const m=await pageOCR(page,c.find);if(!m.length)continue;c.ocrCount=(c.ocrCount||0)+m.length;c.ocrMatches=(c.ocrMatches||[]).concat(m.map(x=>({...x,page:pi+1})));c.pages=c.pages||[];if(!c.pages.includes(pi+1))c.pages.push(pi+1);total+=m.length}}}finally{doc.destroy()}}if(summary){summary.textContent=summary.textContent.replace(/ · \d+ coincidencias? vectorial(?:es)?\/OCR · ningún archivo modificado/,'')+` · ${total} coincidencia${total===1?'':'s'} vectorial/OCR · ningún archivo modificado`;summary.classList.remove('hidden')}if(status)status.textContent=total?`Reconocimiento terminado: ${total} coincidencia${total===1?'':'s'} vectorial/OCR detectada${total===1?'':'s'}. No se ha modificado ningún PDF.`:'Sin coincidencias vectoriales/OCR.';return{total}}
