import * as mupdf from 'https://cdn.jsdelivr.net/npm/mupdf@1.28.0/dist/mupdf.js';
let workerPromise=null;
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[‐‑‒–—−]/g,'-').replace(/\s+/g,' ').trim().toLowerCase();
const key=s=>norm(s).replace(/[^a-z0-9]/g,'').replace(/o/g,'0').replace(/[il]/g,'1');
const lev=(a,b)=>{if(a===b)return 0;let p=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){const q=[i];for(let j=1;j<=b.length;j++)q[j]=Math.min(q[j-1]+1,p[j]+1,p[j-1]+(a[i-1]===b[j-1]?0:1));p=q}return p[b.length]};
const sim=(a,b)=>a&&b?1-lev(a,b)/Math.max(a.length,b.length):0;
const ordered=d=>(d?.words||[]).filter(w=>w?.text?.trim()&&w.bbox).sort((a,b)=>{const ay=(a.bbox.y0+a.bbox.y1)/2,by=(b.bbox.y0+b.bbox.y1)/2,h=Math.max(8,((a.bbox.y1-a.bbox.y0)+(b.bbox.y1-b.bbox.y0))/2);return Math.abs(ay-by)<h*.8?a.bbox.x0-b.bbox.x0:ay-by});
const union=ws=>ws.reduce((b,w)=>{const q=w.bbox;return b?[Math.min(b[0],q.x0),Math.min(b[1],q.y0),Math.max(b[2],q.x1),Math.max(b[3],q.y1)]:[q.x0,q.y0,q.x1,q.y1]},null);
async function worker(){if(workerPromise)return workerPromise;workerPromise=(async()=>{const {createWorker}=await import('https://esm.sh/tesseract.js@5.1.0');const w=await createWorker('eng');await w.setParameters({preserve_interword_spaces:'1',user_defined_dpi:'140',tessedit_pageseg_mode:'11'});return w})().catch(e=>{workerPromise=null;throw e});return workerPromise}
async function recognize(bitmap,mode='11',timeoutMs=30000){const w=await worker();await w.setParameters({tessedit_pageseg_mode:String(mode),preserve_interword_spaces:'1',user_defined_dpi:'140'});let timer;try{return await Promise.race([(async()=>{try{return (await w.recognize(bitmap))?.data||null}catch(e){throw e}})(),new Promise((_,rej)=>{timer=setTimeout(async()=>{try{await w.terminate()}catch(_){}workerPromise=null;rej(new Error('OCR agotó el tiempo de 30 s.'))},timeoutMs)})])}finally{clearTimeout(timer)}}
function matchOne(data,target,scale,ox=0,oy=0){const want=key(target),ws=ordered(data),out=[];if(!want)return out;for(let i=0;i<ws.length;i++){let s='',pick=[];for(let j=i;j<Math.min(ws.length,i+32);j++){pick.push(ws[j]);s+=ws[j].text;const k=key(s),ratio=Math.min(k.length,want.length)/Math.max(k.length,want.length);if(k===want||(ratio>=.78&&sim(k,want)>=.86)){const b=union(pick),conf=Math.min(...pick.map(w=>Number(w.confidence)||50));if(b&&(k===want||conf>=40))out.push({bbox:[(b[0]+ox)/scale,(b[1]+oy)/scale,(b[2]+ox)/scale,(b[3]+oy)/scale],confidence:conf,similarity:sim(k,want),ocrText:s,exact:k===want});break}if(k.length>want.length+40)break}}return out}
function matchAll(data,targets,scale,ox=0,oy=0){const out=new Map();for(const t of targets)out.set(t,matchOne(data,t,scale,ox,oy));return out}
function render(page,maxDim){const b=page.getBounds?.()||[0,0,1000,1000];const w=Math.max(1,b[2]-b[0]),h=Math.max(1,b[3]-b[1]);const scale=Math.min(1.25,Math.max(.65,maxDim/Math.max(w,h)));const pix=page.toPixmap(mupdf.Matrix.scale(scale,scale),mupdf.ColorSpace.DeviceRGB,false,false);return{scale,promise:createImageBitmap(new Blob([pix.asPNG()],{type:'image/png'}))}}
function isHard(t){return key(t).length>=16||String(t).split(/[_\-\s./:]+/).filter(x=>x.length>=2).length>=4}
function anchorsFor(target,data){const anchors=String(target).split(/[_\-\s./:]+/).map(key).filter(x=>x.length>=3).sort((a,b)=>b.length-a.length).slice(0,4),ws=ordered(data),out=[];for(const a of anchors){let best=null;for(const w of ws){const s=sim(key(w.text),a);if(key(w.text)===a||s>=.84){if(!best||s>best.s)best={w,s}}}if(best)out.push(best)}return out}
async function pageOCR(page,targets){const hard=targets.filter(isHard),fast=render(page,1400),bitmap=await fast.promise;try{let data=await recognize(bitmap,'11'),hits=matchAll(data,targets,fast.scale);if([...hits.values()].some(x=>x.length))return hits;if(!hard.length)return hits;const hi=render(page,2200),bm2=await hi.promise;try{data=await recognize(bm2,'11');hits=matchAll(data,targets,hi.scale);if(hard.some(t=>(hits.get(t)||[]).length))return hits;for(const target of hard){for(const a of anchorsFor(target,data)){const q=a.w.bbox,padX=Math.max(180,(q.x1-q.x0)*8),padY=Math.max(70,(q.y1-q.y0)*5),x=Math.max(0,Math.floor(q.x0-padX)),y=Math.max(0,Math.floor(q.y0-padY)),x2=Math.min(bm2.width,Math.ceil(q.x1+padX)),y2=Math.min(bm2.height,Math.ceil(q.y1+padY)),c=document.createElement('canvas');c.width=x2-x;c.height=y2-y;c.getContext('2d').drawImage(bm2,x,y,c.width,c.height,0,0,c.width,c.height);const ad=await recognize(c,'6');const one=matchOne(ad,target,hi.scale,x,y);if(one.length){hits.set(target,one);break}}}return hits}finally{bm2.close?.()}}finally{bitmap.close?.()}}
export async function runRecognition(){const batch=window.__batchAnalysis;if(!Array.isArray(batch)||!batch.length)return{total:0};const status=document.querySelector('#batchStatus'),summary=document.querySelector('#batchSummary');let total=0;for(let ai=0;ai<batch.length;ai++){const a=batch[ai];if(!a||a.error||!a.data||a.kinds?.vector!==true)continue;const pending=(a.counts||[]).filter(c=>c.find?.trim()&&c.count===0&&c.annotationCount===0);if(!pending.length)continue;const doc=mupdf.PDFDocument.openDocument(a.data,'application/pdf');try{const pages=Array.isArray(a.vectorPages)&&a.vectorPages.length?a.vectorPages.map(x=>x-1):[];for(let pi=0;pi<pages.length;pi++){if(status)status.textContent=`OCR rápido · ${ai+1}/${batch.length} · página ${pi+1}/${pages.length} · ${a.name}`;const page=doc.loadPage(pages[pi]);const targets=pending.map(c=>c.find),matches=await pageOCR(page,targets);for(const c of pending){const m=matches.get(c.find)||[];if(!m.length)continue;c.ocrCount=(c.ocrCount||0)+m.length;c.ocrMatches=(c.ocrMatches||[]).concat(m.map(x=>({...x,page:pages[pi]+1})));c.pages=c.pages||[];if(!c.pages.includes(pages[pi]+1))c.pages.push(pages[pi]+1);total+=m.length}}}catch(e){if(status)status.textContent=`OCR detenido: ${e?.message||String(e)}`}finally{doc.destroy()}}if(summary){summary.textContent=summary.textContent.replace(/ · \d+ coincidencias? vectorial(?:es)?\/OCR · ningún archivo modificado/,'')+` · ${total} coincidencia${total===1?'':'s'} vectorial/OCR · ningún archivo modificado`;summary.classList.remove('hidden')}if(status)status.textContent=total?`Reconocimiento terminado: ${total} coincidencia${total===1?'':'s'} vectorial/OCR detectada${total===1?'':'s'}. No se ha modificado ningún PDF.`:'Sin coincidencias vectoriales/OCR.';return{total}}
